# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/audiomuse.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."audiomuse-ai-flask-app" = {
    image = "ghcr.io/neptunehub/audiomuse-ai:latest";
    environment = {
      "POSTGRES_DB" = "audiomusedb";
      "POSTGRES_HOST" = "postgres";
      "POSTGRES_PORT" = "5432";
      "REDIS_URL" = "redis://redis:6379/0";
      "SERVICE_TYPE" = "flask";
      "TEMP_DIR" = "/app/temp_audio";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      config.sops.secrets."compose/audiomuse.env".path
    ];
    volumes = [
      "audiomuse_temp-audio-flask:/app/temp_audio:rw"
    ];
    ports = [
      "8250:8000/tcp"
    ];
    dependsOn = [
      "audiomuse-postgres"
      "audiomuse-redis"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=audiomuse-ai-flask"
      "--network=audiomuse_default"
    ];
  };
  systemd.services."docker-audiomuse-ai-flask-app" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-audiomuse_default.service"
      "docker-volume-audiomuse_temp-audio-flask.service"
    ];
    requires = [
      "docker-network-audiomuse_default.service"
      "docker-volume-audiomuse_temp-audio-flask.service"
    ];
  };
  virtualisation.oci-containers.containers."audiomuse-ai-worker-instance" = {
    image = "ghcr.io/neptunehub/audiomuse-ai:latest";
    environment = {
      "POSTGRES_DB" = "audiomusedb";
      "POSTGRES_HOST" = "postgres";
      "POSTGRES_PORT" = "5432";
      "REDIS_URL" = "redis://redis:6379/0";
      "SERVICE_TYPE" = "worker";
      "TEMP_DIR" = "/app/temp_audio";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      config.sops.secrets."compose/audiomuse.env".path
    ];
    volumes = [
      "audiomuse_temp-audio-worker:/app/temp_audio:rw"
    ];
    dependsOn = [
      "audiomuse-postgres"
      "audiomuse-redis"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=audiomuse-ai-worker"
      "--network=audiomuse_default"
    ];
  };
  systemd.services."docker-audiomuse-ai-worker-instance" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-audiomuse_default.service"
      "docker-volume-audiomuse_temp-audio-worker.service"
    ];
    requires = [
      "docker-network-audiomuse_default.service"
      "docker-volume-audiomuse_temp-audio-worker.service"
    ];
  };
  virtualisation.oci-containers.containers."audiomuse-postgres" = {
    image = "postgres:15-alpine";
    environment = {
      "POSTGRES_DB" = "audiomusedb";
    };
    environmentFiles = [
      config.sops.secrets."compose/audiomuse.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/audiomuse/postgresql:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=postgres"
      "--network=audiomuse_default"
    ];
  };
  systemd.services."docker-audiomuse-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-audiomuse_default.service"
    ];
    requires = [
      "docker-network-audiomuse_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/audiomuse/postgresql"
    ];
  };
  virtualisation.oci-containers.containers."audiomuse-redis" = {
    image = "redis:7-alpine";
    environmentFiles = [
      config.sops.secrets."compose/audiomuse.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/audiomuse/redis:/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=redis"
      "--network=audiomuse_default"
    ];
  };
  systemd.services."docker-audiomuse-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-audiomuse_default.service"
    ];
    requires = [
      "docker-network-audiomuse_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/audiomuse/redis"
    ];
  };

  # Networks
  systemd.services."docker-network-audiomuse_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f audiomuse_default";
    };
    script = ''
      docker network inspect audiomuse_default || docker network create audiomuse_default
    '';
    partOf = [ "docker-compose-audiomuse-root.target" ];
    wantedBy = [ "docker-compose-audiomuse-root.target" ];
  };

  # Volumes
  systemd.services."docker-volume-audiomuse_temp-audio-flask" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker volume rm -f audiomuse_temp-audio-flask";
    };
    script = ''
      docker volume inspect audiomuse_temp-audio-flask || docker volume create audiomuse_temp-audio-flask
    '';
    partOf = [ "docker-compose-audiomuse-root.target" ];
    wantedBy = [ "docker-compose-audiomuse-root.target" ];
  };
  systemd.services."docker-volume-audiomuse_temp-audio-worker" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker volume rm -f audiomuse_temp-audio-worker";
    };
    script = ''
      docker volume inspect audiomuse_temp-audio-worker || docker volume create audiomuse_temp-audio-worker
    '';
    partOf = [ "docker-compose-audiomuse-root.target" ];
    wantedBy = [ "docker-compose-audiomuse-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-audiomuse-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
