# Auto-generated using compose2nix v0.3.1.
{ config, pkgs, lib, homelabMediaPath, ... }:

{
  sops.secrets."compose/simplexchat/smp.env" = {
    sopsFile = ./smp.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."simplexchat-smp-server" = {
    image = "ritiek/smp-server:arm64-0.0.1-test-gh-action";
    environmentFiles = [
      config.sops.secrets."compose/simplexchat/smp.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/simplexchat/smp/config:/etc/opt/simplex:rw"
      "${homelabMediaPath}/services/simplexchat/smp/state:/var/opt/simplex:rw"
    ];
    ports = [
      "5220:5223/tcp"
      "5221:5221"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=smp-server"
      "--network=simplexchat-smp-server_default"
    ];
    labels = {
      "homepage.description" = "Messenger";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:5221";
      "homepage.icon" = "simplex-chat";
      "homepage.name" = "SimpleX Chat";
    };
  };
  systemd.services."docker-simplexchat-smp-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-simplexchat-smp-server_default.service"
    ];
    requires = [
      "docker-network-simplexchat-smp-server_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/simplexchat/smp/config"
      "${homelabMediaPath}/services/simplexchat/smp/state"
    ];
  };

  # Networks
  systemd.services."docker-network-simplexchat-smp-server_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f simplexchat-smp-server_default";
    };
    script = ''
      docker network inspect simplexchat-smp-server_default || docker network create simplexchat-smp-server_default
    '';
    partOf = [ "docker-compose-simplexchat-smp-server-root.target" ];
    wantedBy = [ "docker-compose-simplexchat-smp-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-simplexchat-smp-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
