# Auto-generated using compose2nix v0.3.1.
{ config, pkgs, lib, homelabMediaPath, ... }:

{
  sops.secrets."compose/simplexchat/xftp.env" = {
    sopsFile = ./xftp.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."simplexchat-xftp-server" = {
    image = "ritiek/xftp-server:arm64-0.0.1-test-gh-action";
    environmentFiles = [
      config.sops.secrets."compose/simplexchat/xftp.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/simplexchat/xftp/config:/etc/opt/simplex-xftp:rw"
      "${homelabMediaPath}/services/simplexchat/xftp/files:/srv/xftp:rw"
      "${homelabMediaPath}/services/simplexchat/xftp/state:/var/opt/simplex-xftp:rw"
    ];
    ports = [
      "5219:443/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=xftp-server"
      "--network=simplexchat-xftp-server_default"
    ];
  };
  systemd.services."docker-simplexchat-xftp-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-simplexchat-xftp-server_default.service"
    ];
    requires = [
      "docker-network-simplexchat-xftp-server_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/simplexchat/xftp/config"
      "${homelabMediaPath}/services/simplexchat/xftp/state"
    ];
  };

  # Networks
  systemd.services."docker-network-simplexchat-xftp-server_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f simplexchat-xftp-server_default";
    };
    script = ''
      docker network inspect simplexchat-xftp-server_default || docker network create simplexchat-xftp-server_default
    '';
    partOf = [ "docker-compose-simplexchat-xftp-server-root.target" ];
    wantedBy = [ "docker-compose-simplexchat-xftp-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-simplexchat-xftp-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
