# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/manyfold.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."manyfold" = {
    image = "ghcr.io/manyfold3d/manyfold:latest";
    environmentFiles = [
      config.sops.secrets."compose/manyfold.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/manyfold/models:/models:rw"
    ];
    ports = [
      "3214:3214/tcp"
    ];
    dependsOn = [
      "manyfold-postgres"
      "manyfold-redis"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=app"
      "--network=manyfold_manyfold"
    ];
    labels = {
      "homepage.description" = "3D models";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3214";
      "homepage.icon" = "manyfold";
      "homepage.name" = "Manyfold";
    };
  };
  systemd.services."docker-manyfold" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-manyfold_manyfold.service"
    ];
    requires = [
      "docker-network-manyfold_manyfold.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/manyfold/models"
    ];
  };
  virtualisation.oci-containers.containers."manyfold-postgres" = {
    image = "postgres:15";
    environmentFiles = [
      config.sops.secrets."compose/manyfold.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/manyfold/postgresql:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=postgres"
      "--network=manyfold_manyfold"
    ];
  };
  systemd.services."docker-manyfold-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-manyfold_manyfold.service"
    ];
    requires = [
      "docker-network-manyfold_manyfold.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/manyfold/postgresql"
    ];
  };
  virtualisation.oci-containers.containers."manyfold-redis" = {
    image = "redis:7";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=redis"
      "--network=manyfold_manyfold"
    ];
  };
  systemd.services."docker-manyfold-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-manyfold_manyfold.service"
    ];
    requires = [
      "docker-network-manyfold_manyfold.service"
    ];
  };

  # Networks
  systemd.services."docker-network-manyfold_manyfold" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f manyfold_manyfold";
    };
    script = ''
      docker network inspect manyfold_manyfold || docker network create manyfold_manyfold
    '';
    partOf = [ "docker-compose-manyfold-root.target" ];
    wantedBy = [ "docker-compose-manyfold-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-manyfold-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
