# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  # Configuration
  webUIPort = 3214;
  internalWebUIPort = 13214;

  # Import shared lazy-loading utilities
  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  # Generate lazy-loading services for Manyfold
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Manyfold";
    dockerServiceName = "manyfold";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    refreshInterval = 3;
    requiredMounts = [
      "${homelabMediaPath}/services/manyfold/models"
      "${homelabMediaPath}/services/manyfold/postgresql"
    ];
    rootTarget = "docker-compose-manyfold-root.target";
    # Custom commands for multi-service stack
    startCommand = "systemctl start docker-manyfold-postgres.service docker-manyfold-redis.service docker-manyfold.service";
    stopCommand = "systemctl stop docker-compose-manyfold-root.target";
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets."compose/manyfold.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."manyfold" = {
    image = "ghcr.io/manyfold3d/manyfold:latest";
    environmentFiles = [
      config.sops.secrets."compose/manyfold.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/manyfold/models:/models:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:3214/tcp"
    ];
    dependsOn = [
      "manyfold-postgres"
      "manyfold-redis"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=app"
      "--network=manyfold_manyfold"
    ];
  };
  systemd.services."docker-manyfold" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-manyfold_manyfold.service"
    ];
    requires = [
      "docker-network-manyfold_manyfold.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/manyfold/models"
    ];
    partOf = [ "docker-compose-manyfold-root.target" ];
    wantedBy = [ "docker-compose-manyfold-root.target" ];
  };
  virtualisation.oci-containers.containers."manyfold-postgres" = {
    image = "postgres:15";
    environmentFiles = [
      config.sops.secrets."compose/manyfold.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/manyfold/postgresql:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=postgres"
      "--network=manyfold_manyfold"
    ];
  };
  systemd.services."docker-manyfold-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-manyfold_manyfold.service"
    ];
    requires = [
      "docker-network-manyfold_manyfold.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/manyfold/postgresql"
    ];
    partOf = [ "docker-compose-manyfold-root.target" ];
    wantedBy = [ "docker-compose-manyfold-root.target" ];
  };
  virtualisation.oci-containers.containers."manyfold-redis" = {
    image = "redis:7";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=redis"
      "--network=manyfold_manyfold"
    ];
  };
  systemd.services."docker-manyfold-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-manyfold_manyfold.service"
    ];
    requires = [
      "docker-network-manyfold_manyfold.service"
    ];
    partOf = [ "docker-compose-manyfold-root.target" ];
    wantedBy = [ "docker-compose-manyfold-root.target" ];
  };

  # Networks
  systemd.services."docker-network-manyfold_manyfold" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f manyfold_manyfold";
    };
    script = ''
      docker network inspect manyfold_manyfold || docker network create manyfold_manyfold
    '';
    partOf = [ "docker-compose-manyfold-root.target" ];
    wantedBy = [ "docker-compose-manyfold-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-manyfold-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  }
]
