# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."audiobookshelf" = {
    image = "ghcr.io/advplyr/audiobookshelf:latest";
    environmentFiles = [
      "/home/ritiek/.env"
    ];
    volumes = [
      "${homelabMediaPath}/services/audiobookshelf/audiobooks:/audiobooks:rw"
      "${homelabMediaPath}/services/audiobookshelf/config:/config:rw"
      "${homelabMediaPath}/services/audiobookshelf/metadata:/metadata:rw"
      "${homelabMediaPath}/services/audiobookshelf/podcasts:/podcasts:rw"
      "${homelabMediaPath}/services/calibre/library:/books:rw"
    ];
    ports = [
      "13378:80/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=audiobookshelf"
      "--network=audiobookshelf_default"
    ];
    labels = {
      "homepage.description" = "Read books & listen to audiobooks";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:13378";
      "homepage.icon" = "audiobookshelf";
      "homepage.name" = "Audiobookshelf";
    };
  };
  systemd.services."docker-audiobookshelf" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-audiobookshelf_default.service"
    ];
    requires = [
      "docker-network-audiobookshelf_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/audiobookshelf/audiobooks"
      "${homelabMediaPath}/services/audiobookshelf/config"
      "${homelabMediaPath}/services/audiobookshelf/metadata"
      "${homelabMediaPath}/services/audiobookshelf/podcasts"
      "${homelabMediaPath}/services/calibre/library"
    ];
  };

  # Networks
  systemd.services."docker-network-audiobookshelf_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f audiobookshelf_default";
    };
    script = ''
      docker network inspect audiobookshelf_default || docker network create audiobookshelf_default
    '';
    partOf = [ "docker-compose-audiobookshelf-root.target" ];
    wantedBy = [ "docker-compose-audiobookshelf-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-audiobookshelf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
