# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, homelabMediaPath, ... }:

let
  webUIPort = 13378;
  internalWebUIPort = 13379;

  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Audiobookshelf";
    dockerServiceName = "audiobookshelf";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/audiobookshelf/audiobooks"
      "${homelabMediaPath}/services/audiobookshelf/config"
      "${homelabMediaPath}/services/audiobookshelf/metadata"
      "${homelabMediaPath}/services/audiobookshelf/podcasts"
      "${homelabMediaPath}/services/calibre/library"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."audiobookshelf" = {
    image = "ghcr.io/advplyr/audiobookshelf:latest";
    environmentFiles = [
      "/home/ritiek/.env"
    ];
    volumes = [
      "${homelabMediaPath}/services/audiobookshelf/audiobooks:/audiobooks:rw"
      "${homelabMediaPath}/services/audiobookshelf/config:/config:rw"
      "${homelabMediaPath}/services/audiobookshelf/metadata:/metadata:rw"
      "${homelabMediaPath}/services/audiobookshelf/podcasts:/podcasts:rw"
      "${homelabMediaPath}/services/calibre/library:/books:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:80/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=audiobookshelf"
      "--network=audiobookshelf_default"
    ];
  };
  systemd.services."docker-audiobookshelf" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-audiobookshelf_default.service"
    ];
    requires = [
      "docker-network-audiobookshelf_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/audiobookshelf/audiobooks"
      "${homelabMediaPath}/services/audiobookshelf/config"
      "${homelabMediaPath}/services/audiobookshelf/metadata"
      "${homelabMediaPath}/services/audiobookshelf/podcasts"
      "${homelabMediaPath}/services/calibre/library"
    ];
    partOf = [ "docker-compose-audiobookshelf-root.target" ];
    wantedBy = [ "docker-compose-audiobookshelf-root.target" ];
  };

  # Networks
  systemd.services."docker-network-audiobookshelf_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f audiobookshelf_default";
    };
    script = ''
      docker network inspect audiobookshelf_default || docker network create audiobookshelf_default
    '';
    partOf = [ "docker-compose-audiobookshelf-root.target" ];
    wantedBy = [ "docker-compose-audiobookshelf-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-audiobookshelf-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
