# Auto-generated by compose2nix.

{ pkgs, lib, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."baikal" = {
    image = "ckulka/baikal:nginx";
    volumes = [
      "${homelabMediaPath}/services/baikal/config:/var/www/baikal/config:rw"
      "${homelabMediaPath}/services/baikal/data:/var/www/baikal/Specific:rw"
    ];
    ports = [
      "5880:80/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=baikal"
      "--network=baikal_default"
    ];
    labels = {
      "homepage.description" = "CalDAV & CardDAV server";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:5880";
      "homepage.icon" = "baikal";
      "homepage.name" = "Baikal";
    };
  };
  systemd.services."docker-baikal" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-baikal_default.service"
    ];
    requires = [
      "docker-network-baikal_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/baikal/config"
      "${homelabMediaPath}/services/baikal/data"
    ];
  };

  # Networks
  systemd.services."docker-network-baikal_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f baikal_default";
    };
    script = ''
      docker network inspect baikal_default || docker network create baikal_default
    '';
    partOf = [ "docker-compose-baikal-root.target" ];
    wantedBy = [ "docker-compose-baikal-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-baikal-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
