# Auto-generated by compose2nix.

{ pkgs, lib, homelabMediaPath, ... }:

let
  webUIPort = 5880;
  internalWebUIPort = 15880;

  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Baikal";
    dockerServiceName = "baikal";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/baikal/config"
      "${homelabMediaPath}/services/baikal/data"
    ];
    silent = true;
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."baikal" = {
    image = "ckulka/baikal:nginx";
    volumes = [
      "${homelabMediaPath}/services/baikal/config:/var/www/baikal/config:rw"
      "${homelabMediaPath}/services/baikal/data:/var/www/baikal/Specific:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:80/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=baikal"
      "--network=baikal_default"
    ];
  };
  systemd.services."docker-baikal" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-baikal_default.service"
    ];
    requires = [
      "docker-network-baikal_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/baikal/config"
      "${homelabMediaPath}/services/baikal/data"
    ];
    partOf = [ "docker-compose-baikal-root.target" ];
    wantedBy = [ "docker-compose-baikal-root.target" ];
  };

  # Networks
  systemd.services."docker-network-baikal_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f baikal_default";
    };
    script = ''
      docker network inspect baikal_default || docker network create baikal_default
    '';
    partOf = [ "docker-compose-baikal-root.target" ];
    wantedBy = [ "docker-compose-baikal-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-baikal-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
