# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, servicePaths, everythingElsePath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."bazarr" = {
    image = "lscr.io/linuxserver/bazarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      "/home/ritiek/.env"
    ];
    volumes = [
      "${servicePaths.bazarr.configSource}:/config:rw"
      "${everythingElsePath}/arr/movies:/movies:rw"
      "${everythingElsePath}/arr/tv:/tv:rw"
    ];
    ports = [
      "6767:6767/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=bazarr"
      "--network=bazarr_default"
    ];
    labels = {
      "homepage.description" = "For subtitles";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:6767";
      "homepage.icon" = "bazarr";
      "homepage.name" = "Bazarr";
    };
  };
  systemd.services."docker-bazarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-bazarr_default.service"
    ];
    requires = [
      "docker-network-bazarr_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      servicePaths.bazarr.configSource
      "${everythingElsePath}/arr/movies"
      "${everythingElsePath}/arr/tv"
    ];
  };

  # Networks
  systemd.services."docker-network-bazarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f bazarr_default";
    };
    script = ''
      docker network inspect bazarr_default || docker network create bazarr_default
    '';
    partOf = [ "docker-compose-bazarr-root.target" ];
    wantedBy = [ "docker-compose-bazarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-bazarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
