# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."calibre-web-automated-book-downloader" = {
    image = "ghcr.io/calibrain/calibre-web-automated-book-downloader:latest";
    environment = {
      "APP_ENV" = "prod";
      "BOOK_LANGUAGE" = "en";
      "DOWNLOAD_PROGRESS_UPDATE_INTERVAL" = "5";
      "FLASK_PORT" = "8084";
      "GID" = "1000";
      "LOG_LEVEL" = "info";
      "MAX_CONCURRENT_DOWNLOADS" = "3";
      "TZ" = "Asia/Kolkata";
      "UID" = "1000";
      "USE_BOOK_TITLE" = "true";
    };
    volumes = [
      "${homelabMediaPath}/services/calibre/ingest:/cwa-book-ingest:rw"
      "${homelabMediaPath}/services/calibre/config/app.db:/auth/app.db:ro"
    ];
    ports = [
      "8084:8084/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=calibre-web-automated-book-downloader"
      "--network=calibre-web-automated-book-downloader_default"
    ];
    labels = {
      "homepage.description" = "Book downloader";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:8084";
      "homepage.icon" = "calibre-web";
      "homepage.name" = "Calibre Web Automated Book Downloader";
    };
  };
  systemd.services."docker-calibre-web-automated-book-downloader" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-calibre-web-automated-book-downloader_default.service"
    ];
    requires = [
      "docker-network-calibre-web-automated-book-downloader_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/calibre/ingest"
    ];
  };

  # Networks
  systemd.services."docker-network-calibre-web-automated-book-downloader_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f calibre-web-automated-book-downloader_default";
    };
    script = ''
      docker network inspect calibre-web-automated-book-downloader_default || docker network create calibre-web-automated-book-downloader_default
    '';
    partOf = [ "docker-compose-calibre-web-automated-book-downloader-root.target" ];
    wantedBy = [ "docker-compose-calibre-web-automated-book-downloader-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-calibre-web-automated-book-downloader-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
