# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."copyparty" = {
    image = "copyparty/ac:latest";
    environment = {
      "LD_PRELOAD" = "/usr/lib/libmimalloc-secure.so.NOPE";
      "PYTHONUNBUFFERED" = "1";
    };
    volumes = [
      "/media/HOMELAB_MEDIA:/media/HOMELAB_MEDIA:rw,z"
      "/media/HOMELAB_MEDIA/services/copyparty:/cfg:rw,z"
    ];
    ports = [
      "3923:3923/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=copyparty"
      "--network=copyparty_default"
    ];
    labels = {
      "homepage.description" = "Filebrowser";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3923/";
      "homepage.icon" = "copyparty";
      "homepage.name" = "Copyparty";
    };
  };
  systemd.services."docker-copyparty" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-copyparty_default.service"
    ];
    requires = [
      "docker-network-copyparty_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA"
      "/media/HOMELAB_MEDIA/services/copyparty"
    ];
  };

  # Networks
  systemd.services."docker-network-copyparty_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f copyparty_default";
    };
    script = ''
      docker network inspect copyparty_default || docker network create copyparty_default
    '';
    partOf = [ "docker-compose-copyparty-root.target" ];
    wantedBy = [ "docker-compose-copyparty-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-copyparty-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
