# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, homelabMediaPath, everythingElsePath, ... }:

let
  # Configuration
  webUIPort = 3923;
  internalWebUIPort = 13923;

  # Import shared lazy-loading utilities
  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  # Generate lazy-loading services
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Copyparty";
    dockerServiceName = "copyparty";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    refreshInterval = 3;
    requiredMounts = [
      homelabMediaPath
      "${homelabMediaPath}/services/copyparty"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."copyparty" = {
    image = "copyparty/ac:latest";
    environment = {
      "LD_PRELOAD" = "/usr/lib/libmimalloc-secure.so.NOPE";
      "PYTHONUNBUFFERED" = "1";
    };
    volumes = [
      "${homelabMediaPath}:/mnt/HOMELAB_MEDIA:rw,z"
      "${everythingElsePath}:/mnt/EVERYTHING_ELSE:rw,z"
      "${homelabMediaPath}/services/copyparty:/cfg:rw,z"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:3923/tcp"  # Internal port only
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=copyparty"
      "--network=copyparty_default"
    ];
  };
  # Restore original docker-copyparty service dependencies
  systemd.services."docker-copyparty" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-copyparty_default.service"
    ];
    requires = [
      "docker-network-copyparty_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      homelabMediaPath
      "${homelabMediaPath}/services/copyparty"
    ];
    # Bind to root target
    partOf = [ "docker-compose-copyparty-root.target" ];
    wantedBy = [ "docker-compose-copyparty-root.target" ];
  };

  # Networks
  systemd.services."docker-network-copyparty_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f copyparty_default";
    };
    script = ''
      docker network inspect copyparty_default || docker network create copyparty_default
    '';
    partOf = [ "docker-compose-copyparty-root.target" ];
    wantedBy = [ "docker-compose-copyparty-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-copyparty-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  }
]
