# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."glances" = {
    image = "nicolargo/glances:latest-full";
    environment = {
      "GLANCES_OPT" = "-w";
    };
    volumes = [
      "/etc/os-release:/etc/os-release:ro"
      "/var/run/docker.sock:/var/run/docker.sock:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network=host"
    ];
    labels = {
      "homepage.description" = "System resources";
      "homepage.group" = "Monitoring";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:61208";
      "homepage.icon" = "glances";
      "homepage.name" = "Glances";
    };
  };
  systemd.services."docker-glances" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    unitConfig.RequiresMountsFor = [
      "/etc/os-release"
      "/var/run/docker.sock"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-glances-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
