# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."gotify" = {
    image = "gotify/server-arm64";
    environment = {
      "GOTIFY_DEFAULTUSER_PASS" = "custom";
    };
    volumes = [
      "/media/services/gotify:/app/data:rw"
    ];
    ports = [
      "8893:80/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=gotify"
      "--network=gotify_default"
    ];
  };
  systemd.services."docker-gotify" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-gotify_default.service"
    ];
    requires = [
      "docker-network-gotify_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/services/gotify"
    ];
  };

  # Networks
  systemd.services."docker-network-gotify_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f gotify_default";
    };
    script = ''
      docker network inspect gotify_default || docker network create gotify_default
    '';
    partOf = [ "docker-compose-gotify-root.target" ];
    wantedBy = [ "docker-compose-gotify-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-gotify-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
