# Auto-generated by compose2nix.

{ pkgs, lib, homelabMediaPath, ... }:

let
  # Configuration
  webUIPort = 8822;
  internalWebUIPort = 18822;

  # Import shared lazy-loading utilities
  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  # Generate lazy-loading services
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Gramps Web";
    dockerServiceName = "grampsweb";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    silent = false;
    idleCheckInterval = "*:0/30";  # Every 30 minutes
    startCommand = "systemctl start docker-compose-grampsweb-root.target";
    requiredMounts = [
      "${homelabMediaPath}/services/gramps-web/gramps_cache"
      "${homelabMediaPath}/services/gramps-web/gramps_db"
      "${homelabMediaPath}/services/gramps-web/gramps_index"
      "${homelabMediaPath}/services/gramps-web/gramps_media"
      "${homelabMediaPath}/services/gramps-web/gramps_secret"
      "${homelabMediaPath}/services/gramps-web/gramps_thumb_cache"
      "${homelabMediaPath}/services/gramps-web/gramps_tmp"
      "${homelabMediaPath}/services/gramps-web/gramps_users"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
    # Runtime
    virtualisation.docker = {
      enable = true;
      autoPrune.enable = true;
    };
    virtualisation.oci-containers.backend = "docker";

    # Containers
    virtualisation.oci-containers.containers."grampsweb" = {
      image = "ghcr.io/gramps-project/grampsweb:latest";
      environment = {
        "GRAMPSWEB_CELERY_CONFIG__broker_url" = "redis://grampsweb_redis:6379/0";
        "GRAMPSWEB_CELERY_CONFIG__result_backend" = "redis://grampsweb_redis:6379/0";
        "GRAMPSWEB_RATELIMIT_STORAGE_URI" = "redis://grampsweb_redis:6379/1";
        "GRAMPSWEB_TREE" = "Gramps Web";
      };
      volumes = [
        "${homelabMediaPath}/services/gramps-web/gramps_cache:/app/cache:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_db:/root/.gramps/grampsdb:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_index:/app/indexdir:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_media:/app/media:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_secret:/app/secret:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_thumb_cache:/app/thumbnail_cache:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_tmp:/tmp:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_users:/app/users:rw"
      ];
      ports = [
        "0.0.0.0:${toString internalWebUIPort}:5000/tcp"
      ];
      dependsOn = [
        "grampsweb_redis"
      ];
      log-driver = "journald";
      autoStart = false;
      extraOptions = [
        "--network-alias=grampsweb"
        "--network=grampsweb_default"
      ];
    };
    systemd.services."docker-grampsweb" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-grampsweb_default.service"
      ];
      requires = [
        "docker-network-grampsweb_default.service"
      ];
      unitConfig.RequiresMountsFor = [
        "${homelabMediaPath}/services/gramps-web/gramps_cache"
        "${homelabMediaPath}/services/gramps-web/gramps_db"
        "${homelabMediaPath}/services/gramps-web/gramps_index"
        "${homelabMediaPath}/services/gramps-web/gramps_media"
        "${homelabMediaPath}/services/gramps-web/gramps_secret"
        "${homelabMediaPath}/services/gramps-web/gramps_thumb_cache"
        "${homelabMediaPath}/services/gramps-web/gramps_tmp"
        "${homelabMediaPath}/services/gramps-web/gramps_users"
      ];
      partOf = [ "docker-compose-grampsweb-root.target" ];
      wantedBy = [ "docker-compose-grampsweb-root.target" ];
    };
    virtualisation.oci-containers.containers."grampsweb_celery" = {
      image = "ghcr.io/gramps-project/grampsweb:latest";
      environment = {
        "GRAMPSWEB_CELERY_CONFIG__broker_url" = "redis://grampsweb_redis:6379/0";
        "GRAMPSWEB_CELERY_CONFIG__result_backend" = "redis://grampsweb_redis:6379/0";
        "GRAMPSWEB_RATELIMIT_STORAGE_URI" = "redis://grampsweb_redis:6379/1";
        "GRAMPSWEB_TREE" = "Gramps Web";
      };
      volumes = [
        "${homelabMediaPath}/services/gramps-web/gramps_cache:/app/cache:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_db:/root/.gramps/grampsdb:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_index:/app/indexdir:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_media:/app/media:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_secret:/app/secret:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_thumb_cache:/app/thumbnail_cache:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_tmp:/tmp:rw"
        "${homelabMediaPath}/services/gramps-web/gramps_users:/app/users:rw"
      ];
      cmd = [ "celery" "-A" "gramps_webapi.celery" "worker" "--loglevel=INFO" "--concurrency=2" ];
      dependsOn = [
        "grampsweb"
        "grampsweb_redis"
      ];
      log-driver = "journald";
      autoStart = false;
      extraOptions = [
        "--network-alias=grampsweb_celery"
        "--network=grampsweb_default"
      ];
    };
    systemd.services."docker-grampsweb_celery" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-grampsweb_default.service"
      ];
      requires = [
        "docker-network-grampsweb_default.service"
      ];
      unitConfig.RequiresMountsFor = [
        "${homelabMediaPath}/services/gramps-web/gramps_cache"
        "${homelabMediaPath}/services/gramps-web/gramps_db"
        "${homelabMediaPath}/services/gramps-web/gramps_index"
        "${homelabMediaPath}/services/gramps-web/gramps_media"
        "${homelabMediaPath}/services/gramps-web/gramps_secret"
        "${homelabMediaPath}/services/gramps-web/gramps_thumb_cache"
        "${homelabMediaPath}/services/gramps-web/gramps_tmp"
        "${homelabMediaPath}/services/gramps-web/gramps_users"
      ];
      partOf = [ "docker-compose-grampsweb-root.target" ];
      wantedBy = [ "docker-compose-grampsweb-root.target" ];
    };
    virtualisation.oci-containers.containers."grampsweb_redis" = {
      image = "docker.io/valkey/valkey:8-alpine";
      log-driver = "journald";
      autoStart = false;
      extraOptions = [
        "--network-alias=grampsweb_redis"
        "--network=grampsweb_default"
      ];
    };
    systemd.services."docker-grampsweb_redis" = {
      serviceConfig = {
        Restart = lib.mkOverride 90 "always";
        RestartMaxDelaySec = lib.mkOverride 90 "1m";
        RestartSec = lib.mkOverride 90 "100ms";
        RestartSteps = lib.mkOverride 90 9;
      };
      after = [
        "docker-network-grampsweb_default.service"
      ];
      requires = [
        "docker-network-grampsweb_default.service"
      ];
      partOf = [ "docker-compose-grampsweb-root.target" ];
      wantedBy = [ "docker-compose-grampsweb-root.target" ];
    };

    # Networks
    systemd.services."docker-network-grampsweb_default" = {
      path = [ pkgs.docker ];
      serviceConfig = {
        Type = "oneshot";
        RemainAfterExit = true;
        ExecStop = "docker network rm -f grampsweb_default";
      };
      script = ''
        docker network inspect grampsweb_default || docker network create grampsweb_default
      '';
      partOf = [ "docker-compose-grampsweb-root.target" ];
      wantedBy = [ "docker-compose-grampsweb-root.target" ];
    };

    # Root service
    # When started, this will automatically create all resources and start
    # the containers. When stopped, this will teardown all resources.
    systemd.targets."docker-compose-grampsweb-root" = {
      unitConfig = {
        Description = "Root target generated by compose2nix.";
      };
    };
  }
]
