# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, ... }:

let
  # Configuration
  webUIPort = 3100;
  internalWebUIPort = 13100;

  # Helper script to handle connections
  homeboxConnectionHandler = pkgs.writeShellScript "homebox-connection-handler" ''
    echo "Connection received at $(date)" >&2

    # Check if Homebox container is running
    if ! ${pkgs.systemd}/bin/systemctl is-active --quiet docker-homebox.service; then
      echo "Starting Homebox..." >&2
      ${pkgs.systemd}/bin/systemctl start docker-homebox.service

      # Wait for Homebox to be ready
      echo "Waiting for Homebox to start..." >&2
      for i in $(seq 1 30); do
        if ${pkgs.curl}/bin/curl -s -f --connect-timeout 2 http://127.0.0.1:${toString internalWebUIPort}/ >/dev/null 2>&1; then
          echo "Homebox is ready!" >&2
          break
        fi
        if [ $i -eq 30 ]; then
          echo "Homebox failed to start, sending error page" >&2
          cat << 'EOF'
HTTP/1.1 503 Service Unavailable
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html><head><title>Service Starting</title></head>
<body><h1>Homebox is starting...</h1><p>Please wait a moment and refresh the page.</p></body></html>
EOF
          exit 1
        fi
        sleep 2
      done
    fi

    echo "Homebox is ready, proxying connection..." >&2
    # Now proxy the connection to the running Homebox
    exec ${pkgs.socat}/bin/socat - TCP:127.0.0.1:${toString internalWebUIPort}
  '';

in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."homebox" = {
    image = "ghcr.io/sysadminsmedia/homebox:latest";
    environment = {
      "HBOX_LOG_FORMAT" = "text";
      "HBOX_LOG_LEVEL" = "info";
      "HBOX_WEB_MAX_UPLOAD_SIZE" = "10";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "/media/HOMELAB_MEDIA/services/homebox:/data:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:7745/tcp"  # Internal port only
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=homebox"
      "--network=homebox_default"
    ];
  };
  systemd.services."docker-homebox" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-homebox_default.service"
    ];
    requires = [
      "docker-network-homebox_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/homebox"
    ];
    # Bind to root target
    partOf = [ "docker-compose-homebox-root.target" ];
    wantedBy = [ "docker-compose-homebox-root.target" ];
    # Start timer when service starts, stop when service stops
    postStart = ''
      ${pkgs.systemd}/bin/systemctl start homebox-idle-stop.timer
    '';
    preStop = ''
      ${pkgs.systemd}/bin/systemctl stop homebox-idle-stop.timer || true
    '';
  };

  # Networks
  systemd.services."docker-network-homebox_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f homebox_default";
    };
    script = ''
      docker network inspect homebox_default || docker network create homebox_default
    '';
    partOf = [ "docker-compose-homebox-root.target" ];
    wantedBy = [ "docker-compose-homebox-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-homebox-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  # Port listener that starts Homebox on any connection attempt
  systemd.services."homebox-autostart" = {
    description = "Homebox auto-start on connection";
    serviceConfig = {
      Restart = "always";
      RestartSec = "5s";
    };
    script = ''
      echo "Starting Homebox auto-start proxy on port ${toString webUIPort}..."
      exec ${pkgs.socat}/bin/socat TCP4-LISTEN:${toString webUIPort},reuseaddr,fork EXEC:${homeboxConnectionHandler}
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/homebox"
    ];
    # Bind to root target so it stops when target stops
    partOf = [ "docker-compose-homebox-root.target" ];
    wantedBy = [ "docker-compose-homebox-root.target" ];
    after = [ "docker.service" ];
  };

  # Timer-based service to stop when idle - started manually by docker-homebox
  systemd.timers."homebox-idle-stop" = {
    timerConfig = {
      OnCalendar = "*:0/5";  # Every 5 minutes, more explicit format
      Persistent = true;
      Unit = "homebox-idle-stop.service";
    };
  };

  systemd.services."homebox-idle-stop" = {
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      # Check for active connections (both proxy port and internal port)
      proxy_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString webUIPort}" | grep ESTABLISHED | wc -l)
      internal_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString internalWebUIPort}" | grep ESTABLISHED | wc -l)
      total_connections=$((proxy_connections + internal_connections))

      if [ "$total_connections" -eq 0 ]; then
        echo "$(date): No active connections for 5+ minutes, stopping Homebox"
        ${pkgs.systemd}/bin/systemctl stop docker-homebox.service
        # Timer will automatically stop due to partOf dependency
      else
        echo "$(date): $total_connections active connections, keeping Homebox running"
      fi
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/homebox"
    ];
    # Also bind to root target for additional safety
    partOf = [ "docker-compose-homebox-root.target" ];
  };
}
