# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, everythingElsePath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyseerr" = {
    image = "fallenbagel/jellyseerr:latest";
    environment = {
      "LOG_LEVEL" = "debug";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      "/home/ritiek/.env"
    ];
    volumes = [
      "${everythingElsePath}/downloads/jellyseerr/config:/app/config:rw"
    ];
    ports = [
      "5055:5055/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=jellyseerr"
      "--network=jellyseerr_default"
    ];
    labels = {
      "homepage.description" = "Media requests";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:5055";
      "homepage.icon" = "jellyseerr";
      "homepage.name" = "Jellyseerr";
    };
  };
  systemd.services."docker-jellyseerr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-jellyseerr_default.service"
    ];
    requires = [
      "docker-network-jellyseerr_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${everythingElsePath}/downloads/jellyseerr/config"
    ];
  };

  # Networks
  systemd.services."docker-network-jellyseerr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f jellyseerr_default";
    };
    script = ''
      docker network inspect jellyseerr_default || docker network create jellyseerr_default
    '';
    partOf = [ "docker-compose-jellyseerr-root.target" ];
    wantedBy = [ "docker-compose-jellyseerr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyseerr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
