# Auto-generated using compose2nix v0.3.2.
{ config, pkgs, lib, servicePaths, everythingElsePath, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  services.nfs.server = {
    enable = true;
    exports = ''
      /export/                        *(rw,fsid=0,insecure,no_subtree_check,no_root_squash)
      /export/jellyfin/config         *(rw,nohide,insecure,no_subtree_check,no_root_squash)
      /export/jellyfin/data/movies    *(rw,nohide,insecure,no_subtree_check,no_root_squash)
      /export/jellyfin/data/tvshows   *(rw,nohide,insecure,no_subtree_check,no_root_squash)
    '';
  };
  networking.firewall.allowedTCPPorts = [ 2049 ];   # For NFS^

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "4311";
      "TZ" = "Asia/Kolkata";
      "DOCKER_MODS" = "linuxserver/mods:jellyfin-rffmpeg";
      "RFFMPEG_USER" = "jellyfin";
      "RFFMPEG_HOST" = "mishy.lion-zebra.ts.net";
      "FFMPEG_PATH" = "/usr/local/bin/ffmpeg";
    };
    volumes = [
      "${servicePaths.jellyfin.configSource}:/var/lib/jellyfin:rw"
      # XXX: Also keeping :/config mount for saving log files as I wasn't
      #      able to find a way to change log directory in Jellyfin.
      "${servicePaths.jellyfin.configSource}:/config:rw"

      "${everythingElsePath}/arr/movies:/var/data/jellyfin/movies:rw"
      "${everythingElsePath}/arr/tv:/var/data/jellyfin/tvshows:rw"
      "${homelabMediaPath}/services/spotdl:/var/data/jellyfin/music:rw"
      "${homelabMediaPath}/services/immich/photos/library:/var/data/jellyfin/photos:rw"
      "${homelabMediaPath}/services/calibre/library:/var/data/jellyfin/books:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "8920:8920/tcp"
      "7359:7359/udp"
      "1900:1900/udp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
    ];
    labels = {
      "homepage.description" = "Media server";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:8096";
      "homepage.icon" = "jellyfin";
      "homepage.name" = "Jellyfin";
    };
  };
  systemd.services."docker-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-jellyfin_default.service"
    ];
    requires = [
      "docker-network-jellyfin_default.service"
    ];

    preStart = ''
      ${pkgs.coreutils}/bin/mkdir -p /export/jellyfin/{config,data}

      if ! ${pkgs.util-linux}/bin/mountpoint -q /export/jellyfin/config; then
        ${pkgs.util-linux}/bin/mount --bind ${servicePaths.jellyfin.configSource} /export/jellyfin/config
      fi
      if ! ${pkgs.util-linux}/bin/mountpoint -q /export/jellyfin/data/movies; then
        ${pkgs.coreutils}/bin/mkdir -p /export/jellyfin/data/movies
        ${pkgs.util-linux}/bin/mount --bind ${everythingElsePath}/arr/movies /export/jellyfin/data/movies
      fi
      if ! ${pkgs.util-linux}/bin/mountpoint -q /export/jellyfin/data/tvshows; then
        ${pkgs.coreutils}/bin/mkdir -p /export/jellyfin/data/tvshows
        ${pkgs.util-linux}/bin/mount --bind ${everythingElsePath}/arr/tv /export/jellyfin/data/tvshows
      fi
    '';

    postStop = ''
      ${pkgs.util-linux}/bin/umount /export/jellyfin/data/tvshows 2>/dev/null || true
      ${pkgs.util-linux}/bin/umount /export/jellyfin/data/movies 2>/dev/null || true
      ${pkgs.util-linux}/bin/umount /export/jellyfin/config 2>/dev/null || true
    '';
  };

  # Networks
  systemd.services."docker-network-jellyfin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f jellyfin_default";
    };
    script = ''
      docker network inspect jellyfin_default || docker network create jellyfin_default
    '';
    partOf = [ "docker-compose-jellyfin-root.target" ];
    wantedBy = [ "docker-compose-jellyfin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
