# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, everythingElsePath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."jellyfin" = {
    image = "lscr.io/linuxserver/jellyfin:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      "/home/ritiek/.env"
    ];
    volumes = [
      "${everythingElsePath}/downloads/jellyfin/config:/config:rw"
      "${everythingElsePath}/downloads/radarr/movies:/data/movies:rw"
      "${everythingElsePath}/downloads/sonarr/tv:/data/tvshows:rw"
    ];
    ports = [
      "8096:8096/tcp"
      "8920:8920/tcp"
      "7359:7359/udp"
      "1900:1900/udp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=jellyfin"
      "--network=jellyfin_default"
    ];
    labels = {
      "homepage.description" = "Media server";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:8096";
      "homepage.icon" = "jellyfin";
      "homepage.name" = "Jellyfin";
    };
  };
  systemd.services."docker-jellyfin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-jellyfin_default.service"
    ];
    requires = [
      "docker-network-jellyfin_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${everythingElsePath}/downloads/jellyfin/config"
      "${everythingElsePath}/downloads/radarr/movies"
      "${everythingElsePath}/downloads/sonarr/tv"
    ];
  };

  # Networks
  systemd.services."docker-network-jellyfin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f jellyfin_default";
    };
    script = ''
      docker network inspect jellyfin_default || docker network create jellyfin_default
    '';
    partOf = [ "docker-compose-jellyfin-root.target" ];
    wantedBy = [ "docker-compose-jellyfin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-jellyfin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
