# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, ... }:

let
  # Configuration
  webUIPort = 5230;
  internalWebUIPort = 15230;

  # Helper script to handle connections
  memosConnectionHandler = pkgs.writeShellScript "memos-connection-handler" ''
    echo "Connection received at $(date)" >&2

    # Check if Memos container is running
    if ! ${pkgs.systemd}/bin/systemctl is-active --quiet docker-memos.service; then
      echo "Starting Memos container..." >&2
      ${pkgs.systemd}/bin/systemctl start docker-memos.service

      # Wait for Memos to be ready
      echo "Waiting for Memos to start..." >&2
      for i in $(seq 1 30); do
        if ${pkgs.curl}/bin/curl -s -f --connect-timeout 2 http://127.0.0.1:${toString internalWebUIPort}/ >/dev/null 2>&1; then
          echo "Memos is ready!" >&2
          break
        fi
        if [ $i -eq 30 ]; then
          echo "Memos failed to start, sending error page" >&2
          cat << 'EOF'
HTTP/1.1 503 Service Unavailable
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html><head><title>Service Starting</title></head>
<body><h1>Memos is starting...</h1><p>Please wait a moment and refresh the page.</p></body></html>
EOF
          exit 1
        fi
        sleep 2
      done
    fi

    echo "Memos is ready, proxying connection..." >&2
    # Now proxy the connection to the running Memos
    exec ${pkgs.socat}/bin/socat - TCP:127.0.0.1:${toString internalWebUIPort}
  '';

in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."memos" = {
    image = "neosmemo/memos:latest";
    volumes = [
      "/media/HOMELAB_MEDIA/services/memos:/var/opt/memos:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:5230/tcp"  # Internal port only
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=memos"
      "--network=memos_default"
    ];
  };
  # Restore original docker-memos service dependencies
  systemd.services."docker-memos" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-memos_default.service"
    ];
    requires = [
      "docker-network-memos_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/memos"
    ];
    # Bind to root target
    partOf = [ "docker-compose-memos-root.target" ];
    wantedBy = [ "docker-compose-memos-root.target" ];
    # Start timer when service starts, stop when service stops
    postStart = ''
      ${pkgs.systemd}/bin/systemctl start memos-idle-stop.timer
    '';
    preStop = ''
      ${pkgs.systemd}/bin/systemctl stop memos-idle-stop.timer || true
    '';
  };

  # Networks
  systemd.services."docker-network-memos_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f memos_default";
    };
    script = ''
      docker network inspect memos_default || docker network create memos_default
    '';
    partOf = [ "docker-compose-memos-root.target" ];
    wantedBy = [ "docker-compose-memos-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-memos-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  # Port listener that starts Memos on any connection attempt
  systemd.services."memos-autostart" = {
    description = "Memos auto-start on connection";
    serviceConfig = {
      Restart = "always";
      RestartSec = "5s";
    };
    script = ''
      echo "Starting Memos auto-start proxy on port ${toString webUIPort}..."
      exec ${pkgs.socat}/bin/socat TCP4-LISTEN:${toString webUIPort},reuseaddr,fork EXEC:${memosConnectionHandler}
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/memos"
    ];
    # Bind to root target so it stops when target stops
    partOf = [ "docker-compose-memos-root.target" ];
    wantedBy = [ "docker-compose-memos-root.target" ];
    after = [ "docker.service" ];
  };

  # Timer-based service to stop when idle - started manually by docker-memos
  systemd.timers."memos-idle-stop" = {
    timerConfig = {
      OnCalendar = "*:0/5";  # Every 5 minutes, more explicit format
      Persistent = true;
      Unit = "memos-idle-stop.service";
    };
  };

  systemd.services."memos-idle-stop" = {
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      # Check for active connections (both proxy port and internal port)
      proxy_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString webUIPort}" | grep ESTABLISHED | wc -l)
      internal_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString internalWebUIPort}" | grep ESTABLISHED | wc -l)
      total_connections=$((proxy_connections + internal_connections))

      if [ "$total_connections" -eq 0 ]; then
        echo "$(date): No active connections for 5+ minutes, stopping Memos"
        ${pkgs.systemd}/bin/systemctl stop docker-memos.service
        # Timer will automatically stop due to partOf dependency
      else
        echo "$(date): $total_connections active connections, keeping Memos running"
      fi
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/memos"
    ];
    # Also bind to root target for additional safety
    partOf = [ "docker-compose-memos-root.target" ];
  };
}
