# Auto-generated by compose2nix.

{ pkgs, lib, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."meshmonitor" = {
    image = "ghcr.io/yeraze/meshmonitor:latest";
    environment = {
      "ALLOWED_ORIGINS" = "*";
      "MESHTASTIC_NODE_IP" = "serial-bridge";
      "ENABLE_VIRTUAL_NODE" = "true";
      "VIRTUAL_NODE_ALLOW_ADMIN_COMMANDS" = "true";
      "DISABLE_ANONYMOUS" = "true";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "${homelabMediaPath}/services/meshmonitor:/data:rw"
    ];
    ports = [
      "5819:3001/tcp"
      "4404:4404/tcp"
    ];
    dependsOn = [
      "meshtastic-serial-bridge"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=meshmonitor"
      "--network=meshmonitor_default"
    ];
    labels = {
      "homepage.description" = "Manage Meshtastic devices";
      "homepage.group" = "Monitoring";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:5819";
      "homepage.icon" = "meshmonitor";
      "homepage.name" = "MeshMonitor";
    };
  };
  systemd.services."docker-meshmonitor" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-meshmonitor_default.service"
    ];
    requires = [
      "docker-network-meshmonitor_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/meshmonitor"
    ];
  };
  virtualisation.oci-containers.containers."meshtastic-serial-bridge" = {
    image = "ghcr.io/yeraze/meshtastic-serial-bridge:latest";
    environment = {
      "BAUD_RATE" = "115200";
      "SERIAL_DEVICE" = "/dev/ttyACM0";
      "TCP_PORT" = "4403";
    };
    ports = [
      "4403:4403/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--device=/dev/ttyACM0:/dev/ttyACM0:rwm"
      "--network-alias=serial-bridge"
      "--network=meshmonitor_default"
    ];
    labels = {
      "homepage.description" = "Meshtastic serial bridge";
      "homepage.group" = "Monitoring";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:4403";
      "homepage.icon" = "meshmonitor";
      "homepage.name" = "Meshtastic Serial Bridge";
    };
  };
  systemd.services."docker-meshtastic-serial-bridge" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-meshmonitor_default.service"
    ];
    requires = [
      "docker-network-meshmonitor_default.service"
    ];
  };
  virtualisation.oci-containers.containers."mqtt-proxy" = {
    image = "ghcr.io/ln4cy/mqtt-proxy:master";
    environment = {
      "INTERFACE_TYPE" = "tcp";
      "TCP_NODE_HOST" = "meshmonitor";
      "TCP_NODE_PORT" = "4404";
      "LOG_LEVEL" = "INFO";
      "TCP_TIMEOUT" = "300";
      "CONFIG_WAIT_TIMEOUT" = "60";
      "HEALTH_CHECK_ACTIVITY_TIMEOUT" = "300";
    };
    dependsOn = [
      "meshmonitor"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=[\"CMD-SHELL\",\"test -f /tmp/healthy && find /tmp/healthy -mmin -1 | grep -q healthy\"]"
      "--health-interval=30s"
      "--health-retries=3"
      "--health-start-period=60s"
      "--health-timeout=10s"
      "--network-alias=mqtt-proxy"
      "--network=meshmonitor_default"
    ];
  };
  systemd.services."docker-mqtt-proxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-meshmonitor_default.service"
    ];
    requires = [
      "docker-network-meshmonitor_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-meshmonitor_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f meshmonitor_default";
    };
    script = ''
      docker network inspect meshmonitor_default || docker network create meshmonitor_default
    '';
    partOf = [ "docker-compose-meshmonitor-root.target" ];
    wantedBy = [ "docker-compose-meshmonitor-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-meshmonitor-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
