# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, homelabMediaPath, ... }:

let
  # Configuration
  webUIPort = 4533;
  internalWebUIPort = 14533;

  # Import shared lazy-loading utilities
  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  # Generate lazy-loading services
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Navidrome";
    dockerServiceName = "navidrome";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    refreshInterval = 3;
    silent = true;
    requiredMounts = [
      "${homelabMediaPath}/services/navidrome"
      "${homelabMediaPath}/services/spotdl"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  virtualisation.oci-containers.containers."navidrome" = {
    image = "deluan/navidrome:latest";
    environment = {
      "ND_BASEURL" = "";
      "ND_LOGLEVEL" = "info";
      "ND_SCANSCHEDULE" = "1h";
      "ND_SESSIONTIMEOUT" = "24h";
      "ND_PLUGINS_ENABLED" = "true";
      "ND_PLUGINS_AUTORELOAD" = "true";
      "ND_AGENTS" = "audiomuseai,lastfm,spotify,deezer";
      "ND_DEVARTISTINFOTIMETOLIVE" = "1s";
    };
    volumes = [
      "${homelabMediaPath}/services/navidrome:/data:rw"
      "${homelabMediaPath}/services/spotdl:/music:ro"
    ];
    ports = [ "0.0.0.0:${toString internalWebUIPort}:4533/tcp" ];  # Bind on all interfaces so Docker DNAT works for container-to-container access
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=navidrome"
      "--network=navidrome_default"
    ];
  };

  # Network
  systemd.services."docker-network-navidrome_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f navidrome_default";
    };
    script = ''
      docker network inspect navidrome_default || docker network create navidrome_default
    '';
    partOf = [ "docker-compose-navidrome-root.target" ];
    wantedBy = [ "docker-compose-navidrome-root.target" ];
  };

  # Restore original docker-navidrome service dependencies
  systemd.services."docker-navidrome" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-navidrome_default.service"
    ];
    requires = [
      "docker-network-navidrome_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/navidrome"
      "${homelabMediaPath}/services/spotdl"
    ];
    # Bind to root target
    partOf = [ "docker-compose-navidrome-root.target" ];
    wantedBy = [ "docker-compose-navidrome-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-navidrome-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  }
]
