# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."nitter" = {
    image = "zedeus/nitter:latest-arm64";
    volumes = [
      "/media/HOMELAB_MEDIA/services/nitter/nitter.conf:/src/nitter.conf:rw"
      "/media/HOMELAB_MEDIA/services/nitter/sessions.jsonl:/src/sessions.jsonl:rw"
    ];
    ports = [
      "5095:8080/tcp"
    ];
    dependsOn = [
      "redis-nitter"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=nitter"
      "--network=nitter_default"
    ];
    labels = {
      "homepage.description" = "X Frontend";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:5095/";
      "homepage.icon" = "nitter";
      "homepage.name" = "Nitter";
    };
  };
  systemd.services."docker-nitter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-nitter_default.service"
    ];
    requires = [
      "docker-network-nitter_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/etc/nixos/nitter.conf"
      "/etc/nixos/sessions.jsonl"
    ];
  };
  virtualisation.oci-containers.containers."redis-nitter" = {
    image = "redis:alpine";
    cmd = [ "redis-server" "--save" "60" "1" "--loglevel" "warning" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=redis-nitter"
      "--network=nitter_default"
    ];
  };
  systemd.services."docker-redis-nitter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-nitter_default.service"
    ];
    requires = [
      "docker-network-nitter_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-nitter_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f nitter_default";
    };
    script = ''
      docker network inspect nitter_default || docker network create nitter_default
    '';
    partOf = [ "docker-compose-nitter-root.target" ];
    wantedBy = [ "docker-compose-nitter-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-nitter-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
