# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, ... }:

let
  # Configuration
  webUIPort = 5095;
  internalWebUIPort = 15095;

  # Helper script to handle connections
  nitterConnectionHandler = pkgs.writeShellScript "nitter-connection-handler" ''
    echo "Connection received at $(date)" >&2

    # Check if Nitter container is running
    if ! ${pkgs.systemd}/bin/systemctl is-active --quiet docker-nitter.service; then
      echo "Starting Nitter stack..." >&2
      ${pkgs.systemd}/bin/systemctl start docker-redis-nitter.service
      ${pkgs.systemd}/bin/systemctl start docker-nitter.service

      # Wait for Nitter to be ready
      echo "Waiting for Nitter to start..." >&2
      for i in $(seq 1 45); do
        if ${pkgs.curl}/bin/curl -s -f --connect-timeout 2 http://127.0.0.1:${toString internalWebUIPort}/ >/dev/null 2>&1; then
          echo "Nitter is ready!" >&2
          break
        fi
        if [ $i -eq 45 ]; then
          echo "Nitter failed to start, sending error page" >&2
          cat << 'EOF'
HTTP/1.1 503 Service Unavailable
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html><head><title>Service Starting</title></head>
<body><h1>Nitter is starting...</h1><p>Please wait a moment and refresh the page.</p></body></html>
EOF
          exit 1
        fi
        sleep 3
      done
    fi

    echo "Nitter is ready, proxying connection..." >&2
    # Now proxy the connection to the running Nitter
    exec ${pkgs.socat}/bin/socat - TCP:127.0.0.1:${toString internalWebUIPort}
  '';

in {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."nitter" = {
    image = "zedeus/nitter:latest-arm64";
    volumes = [
      "/media/HOMELAB_MEDIA/services/nitter/nitter.conf:/src/nitter.conf:rw"
      "/media/HOMELAB_MEDIA/services/nitter/sessions.jsonl:/src/sessions.jsonl:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8080/tcp"  # Internal port only
    ];
    dependsOn = [
      "redis-nitter"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=nitter"
      "--network=nitter_default"
    ];
  };
  systemd.services."docker-nitter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-nitter_default.service"
    ];
    requires = [
      "docker-network-nitter_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/nitter/nitter.conf"
      "/media/HOMELAB_MEDIA/services/nitter/sessions.jsonl"
    ];
    # Bind to root target
    partOf = [ "docker-compose-nitter-root.target" ];
    wantedBy = [ "docker-compose-nitter-root.target" ];
    # Start timer when service starts, stop when service stops
    postStart = ''
      ${pkgs.systemd}/bin/systemctl start nitter-idle-stop.timer
    '';
    preStop = ''
      ${pkgs.systemd}/bin/systemctl stop nitter-idle-stop.timer || true
    '';
  };
  virtualisation.oci-containers.containers."redis-nitter" = {
    image = "redis:alpine";
    cmd = [ "redis-server" "--save" "60" "1" "--loglevel" "warning" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=redis-nitter"
      "--network=nitter_default"
    ];
  };
  systemd.services."docker-redis-nitter" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-nitter_default.service"
    ];
    requires = [
      "docker-network-nitter_default.service"
    ];
    # Bind to root target
    partOf = [ "docker-compose-nitter-root.target" ];
    wantedBy = [ "docker-compose-nitter-root.target" ];
  };

  # Networks
  systemd.services."docker-network-nitter_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f nitter_default";
    };
    script = ''
      docker network inspect nitter_default || docker network create nitter_default
    '';
    partOf = [ "docker-compose-nitter-root.target" ];
    wantedBy = [ "docker-compose-nitter-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-nitter-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  # Port listener that starts Nitter on any connection attempt
  systemd.services."nitter-autostart" = {
    description = "Nitter auto-start on connection";
    serviceConfig = {
      Restart = "always";
      RestartSec = "5s";
    };
    script = ''
      echo "Starting Nitter auto-start proxy on port ${toString webUIPort}..."
      exec ${pkgs.socat}/bin/socat TCP4-LISTEN:${toString webUIPort},reuseaddr,fork EXEC:${nitterConnectionHandler}
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/nitter/nitter.conf"
      "/media/HOMELAB_MEDIA/services/nitter/sessions.jsonl"
    ];
    # Bind to root target so it stops when target stops
    partOf = [ "docker-compose-nitter-root.target" ];
    wantedBy = [ "docker-compose-nitter-root.target" ];
    after = [ "docker.service" ];
  };

  # Timer-based service to stop when idle - started manually by docker-nitter
  systemd.timers."nitter-idle-stop" = {
    timerConfig = {
      OnCalendar = "*:0/5";  # Every 5 minutes, more explicit format
      Persistent = true;
      Unit = "nitter-idle-stop.service";
    };
  };

  systemd.services."nitter-idle-stop" = {
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      # Check for active connections (both proxy port and internal port)
      proxy_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString webUIPort}" | grep ESTABLISHED | wc -l)
      internal_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString internalWebUIPort}" | grep ESTABLISHED | wc -l)
      total_connections=$((proxy_connections + internal_connections))

      if [ "$total_connections" -eq 0 ]; then
        echo "$(date): No active connections for 5+ minutes, stopping Nitter stack"
        ${pkgs.systemd}/bin/systemctl stop docker-nitter.service
        ${pkgs.systemd}/bin/systemctl stop docker-redis-nitter.service
        # Timer will automatically stop due to partOf dependency
      else
        echo "$(date): $total_connections active connections, keeping Nitter running"
      fi
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/nitter/nitter.conf"
      "/media/HOMELAB_MEDIA/services/nitter/sessions.jsonl"
    ];
    # Also bind to root target for additional safety
    partOf = [ "docker-compose-nitter-root.target" ];
  };
}
