# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, config, everythingElsePath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."prowlarr" = {
    image = "lscr.io/linuxserver/prowlarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "${everythingElsePath}/downloads/prowlarr/config:/config:rw"
    ];
    ports = [
      "9696:9696/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=prowlarr"
      "--network=prowlarr_default"
    ];
    labels = {
      "homepage.description" = "For indexers";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:9696";
      "homepage.icon" = "prowlarr";
      "homepage.name" = "Prowlarr";
    };
  };
  systemd.services."docker-prowlarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-prowlarr_default.service"
    ];
    requires = [
      "docker-network-prowlarr_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${everythingElsePath}/downloads/prowlarr/config"
    ];
  };

  # Networks
  systemd.services."docker-network-prowlarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f prowlarr_default";
    };
    script = ''
      docker network inspect prowlarr_default || docker network create prowlarr_default
    '';
    partOf = [ "docker-compose-prowlarr-root.target" ];
    wantedBy = [ "docker-compose-prowlarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-prowlarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
