# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, everythingElsePath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."qbittorrent" = {
    image = "lscr.io/linuxserver/qbittorrent:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TORRENTING_PORT" = "6881";
      "TZ" = "Asia/Kolkata";
      "WEBUI_PORT" = "9082";
    };
    volumes = [
      "${everythingElsePath}/qbittorrent/config:/config:rw"
      "${everythingElsePath}/qbittorrent/downloads:/downloads:rw"
    ];
    ports = [
      "9082:9082/tcp"
      "6881:6881/tcp"
      "6881:6881/udp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=qbittorrent"
      "--network=qbittorrent_default"
    ];
    labels = {
      "homepage.description" = "Torrent downloads";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:9082";
      "homepage.icon" = "qbittorrent";
      "homepage.name" = "qBittorrent";
    };
  };
  systemd.services."docker-qbittorrent" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-qbittorrent_default.service"
    ];
    requires = [
      "docker-network-qbittorrent_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${everythingElsePath}/qbittorrent/config"
      "${everythingElsePath}/qbittorrent/downloads"
    ];
  };

  # Networks
  systemd.services."docker-network-qbittorrent_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f qbittorrent_default";
    };
    script = ''
      docker network inspect qbittorrent_default || docker network create qbittorrent_default
    '';
    partOf = [ "docker-compose-qbittorrent-root.target" ];
    wantedBy = [ "docker-compose-qbittorrent-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-qbittorrent-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
