# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 2399;
  internalWebUIPort = 12399;

  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Readeck";
    dockerServiceName = "readeck";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    silent = true;
    idleCheckInterval = "*:0/15";  # Every 15 minutes
    requiredMounts = [
      "${homelabMediaPath}/services/readeck"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Allow Docker containers to reach the lazy-loading socat proxy via host.docker.internal.
  # The socat listener binds to 0.0.0.0, so opening the port globally is sufficient.
  # External access is blocked at the network perimeter (not exposed to WAN).
  networking.firewall.allowedTCPPorts = [ webUIPort ];

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."readeck" = {
    image = "codeberg.org/readeck/readeck:latest";
    volumes = [
      "${homelabMediaPath}/services/readeck:/readeck:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8000/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=${lib.head (lib.splitString "/" config.virtualisation.docker.daemon.settings.bip)}"
      "--network-alias=readeck"
      "--network=readeck_default"
    ];
  };
  systemd.services."docker-readeck" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-readeck_default.service"
    ];
    requires = [
      "docker-network-readeck_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/readeck"
    ];
    partOf = [ "docker-compose-readeck-root.target" ];
    wantedBy = [ "docker-compose-readeck-root.target" ];
  };

  # Networks
  systemd.services."docker-network-readeck_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f readeck_default";
    };
    script = ''
      docker network inspect readeck_default || docker network create readeck_default
    '';
    partOf = [ "docker-compose-readeck-root.target" ];
    wantedBy = [ "docker-compose-readeck-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-readeck-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
