# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

let
  webUIPort = 6020;
  internalWebUIPort = 16020;

  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Redlib";
    dockerServiceName = "redlib";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    healthEndpoint = "/settings";
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."redlib" = {
    image = "quay.io/redlib/redlib:latest";
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8080/tcp"
    ];
    user = "nobody";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--cap-drop=ALL"
      "--health-cmd=[\"wget\", \"--spider\", \"-q\", \"--tries=1\", \"http://localhost:8080/settings\"]"
      "--health-interval=5m0s"
      "--health-timeout=3s"
      "--network-alias=redlib"
      "--network=redlib_default"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."docker-redlib" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-redlib_default.service"
    ];
    requires = [
      "docker-network-redlib_default.service"
    ];
    partOf = [ "docker-compose-redlib-root.target" ];
    wantedBy = [ "docker-compose-redlib-root.target" ];
  };

  # Networks
  systemd.services."docker-network-redlib_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f redlib_default";
    };
    script = ''
      docker network inspect redlib_default || docker network create redlib_default
    '';
    partOf = [ "docker-compose-redlib-root.target" ];
    wantedBy = [ "docker-compose-redlib-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-redlib-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
