# Auto-generated by compose2nix.

{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."redlib" = {
    image = "quay.io/redlib/redlib:latest";
    ports = [
      "6020:8080/tcp"
    ];
    user = "nobody";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--cap-drop=ALL"
      "--health-cmd=[\"wget\", \"--spider\", \"-q\", \"--tries=1\", \"http://localhost:8080/settings\"]"
      "--health-interval=5m0s"
      "--health-timeout=3s"
      "--network-alias=redlib"
      "--network=redlib_default"
      "--security-opt=no-new-privileges:true"
    ];
    labels = {
      "homepage.description" = "Reddit";
      "homepage.group" = "Frontends";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:6020";
      "homepage.icon" = "redlib";
      "homepage.name" = "Redlib";
    };
  };
  systemd.services."docker-redlib" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-redlib_default.service"
    ];
    requires = [
      "docker-network-redlib_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-redlib_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f redlib_default";
    };
    script = ''
      docker network inspect redlib_default || docker network create redlib_default
    '';
    partOf = [ "docker-compose-redlib-root.target" ];
    wantedBy = [ "docker-compose-redlib-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-redlib-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
