# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 3025;
  internalWebUIPort = 13025;

  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Scriberr";
    dockerServiceName = "scriberr";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/scriberr/data"
      "${homelabMediaPath}/services/scriberr/env"
    ];
    idleCheckInterval = "*-*-* 0/6:00:00";
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."scriberr" = {
    image = "ghcr.io/rishikanthc/scriberr:latest";
    environment = {
      "APP_ENV" = "production";
      "SECURE_COOKIES" = "false";
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "${homelabMediaPath}/services/scriberr/data:/app/data:rw"
      "${homelabMediaPath}/services/scriberr/env:/app/whisperx-env:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8080/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=scriberr"
      "--network=scriberr_default"
    ];
  };
  systemd.services."docker-scriberr" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-scriberr_default.service"
    ];
    requires = [
      "docker-network-scriberr_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/scriberr/data"
      "${homelabMediaPath}/services/scriberr/env"
    ];
    partOf = [ "docker-compose-scriberr-root.target" ];
    wantedBy = [ "docker-compose-scriberr-root.target" ];
  };

  # Networks
  systemd.services."docker-network-scriberr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f scriberr_default";
    };
    script = ''
      docker network inspect scriberr_default || docker network create scriberr_default
    '';
    partOf = [ "docker-compose-scriberr-root.target" ];
    wantedBy = [ "docker-compose-scriberr-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-scriberr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
