# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."scriberr" = {
    image = "ghcr.io/rishikanthc/scriberr:latest";
    environment = {
      "APP_ENV" = "production";
      "SECURE_COOKIES" = "false";
      "PGID" = "1000";
      "PUID" = "1000";
    };
    volumes = [
      "${homelabMediaPath}/services/scriberr/data:/app/data:rw"
      "${homelabMediaPath}/services/scriberr/env:/app/whisperx-env:rw"
    ];
    ports = [
      "3025:8080/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=scriberr"
      "--network=scriberr_default"
    ];
    labels = {
      "homepage.description" = "Audio transcriptions";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3025";
      "homepage.icon" = "scriberr";
      "homepage.name" = "Scriberr";
    };
  };
  systemd.services."docker-scriberr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-scriberr_default.service"
    ];
    requires = [
      "docker-network-scriberr_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/scriberr/data"
      "${homelabMediaPath}/services/scriberr/env"
    ];
  };

  # Networks
  systemd.services."docker-network-scriberr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f scriberr_default";
    };
    script = ''
      docker network inspect scriberr_default || docker network create scriberr_default
    '';
    partOf = [ "docker-compose-scriberr-root.target" ];
    wantedBy = [ "docker-compose-scriberr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-scriberr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
