# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 6040;
  internalWebUIPort = 16040;

  lazyLoadingLib = import ./lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "SearXNG";
    dockerServiceName = "searxng";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/searxng/cache"
      "${homelabMediaPath}/services/searxng/config"
    ];
    silent = true;
    startCommand = "systemctl start docker-redis.service docker-searxng.service";
    stopCommand = "systemctl stop docker-compose-searxng-root.target";
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."searxng" = {
    image = "docker.io/searxng/searxng:latest";
    environment = {
      "SEARXNG_BASE_URL" = "http://pilab.lion-zebra.ts.net:6040/";
      "SEARXNG_HOSTNAME" = "pilab.lion-zebra.ts.net";
    };
    volumes = [
      "${homelabMediaPath}/services/searxng/cache:/var/cache/searxng:rw"
      "${homelabMediaPath}/services/searxng/config:/etc/searxng:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8080/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=100.100.100.100"
      "--dns=1.1.1.1"
      "--dns=8.8.8.8"
      "--network-alias=searxng"
      "--network=searxng_searxng"
    ];
  };
  systemd.services."docker-searxng" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-searxng_searxng.service"
    ];
    requires = [
      "docker-network-searxng_searxng.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/searxng/cache"
      "${homelabMediaPath}/services/searxng/config"
    ];
    partOf = [ "docker-compose-searxng-root.target" ];
    wantedBy = [ "docker-compose-searxng-root.target" ];
  };
  virtualisation.oci-containers.containers."redis" = {
    image = "docker.io/valkey/valkey:8-alpine";
    volumes = [
      "${homelabMediaPath}/searxng/redis:/data:rw"
    ];
    cmd = [ "valkey-server" "--save" "30" "1" "--loglevel" "warning" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=redis"
      "--network=searxng_searxng"
    ];
  };
  systemd.services."docker-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-searxng_searxng.service"
    ];
    requires = [
      "docker-network-searxng_searxng.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/searxng/redis"
    ];
    partOf = [ "docker-compose-searxng-root.target" ];
    wantedBy = [ "docker-compose-searxng-root.target" ];
  };

  # Networks
  systemd.services."docker-network-searxng_searxng" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f searxng_searxng";
    };
    script = ''
      docker network inspect searxng_searxng || docker network create searxng_searxng
    '';
    partOf = [ "docker-compose-searxng-root.target" ];
    wantedBy = [ "docker-compose-searxng-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-searxng-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
