# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."redis" = {
    image = "docker.io/valkey/valkey:8-alpine";
    volumes = [
      "${homelabMediaPath}/searxng/redis:/data:rw"
    ];
    cmd = [ "valkey-server" "--save" "30" "1" "--loglevel" "warning" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=redis"
      "--network=searxng_searxng"
    ];
    labels = {
      "homepage.description" = "Meta search engine";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:6040";
      "homepage.icon" = "searxng";
      "homepage.name" = "SearXNG";
    };
  };
  systemd.services."docker-redis" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-searxng_searxng.service"
    ];
    requires = [
      "docker-network-searxng_searxng.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/searxng/redis"
    ];
  };
  virtualisation.oci-containers.containers."searxng" = {
    image = "docker.io/searxng/searxng:latest";
    environment = {
      "SEARXNG_BASE_URL" = "http://pilab.lion-zebra.ts.net:6040/";
      "SEARXNG_HOSTNAME" = "pilab.lion-zebra.ts.net";
    };
    volumes = [
      "${homelabMediaPath}/services/searxng/cache:/var/cache/searxng:rw"
      "${homelabMediaPath}/services/searxng/config:/etc/searxng:rw"
    ];
    ports = [
      "6040:8080/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=searxng"
      "--network=searxng_searxng"
    ];
  };
  systemd.services."docker-searxng" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-searxng_searxng.service"
    ];
    requires = [
      "docker-network-searxng_searxng.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/searxng/cache"
      "${homelabMediaPath}/services/searxng/config"
    ];
  };

  # Networks
  systemd.services."docker-network-searxng_searxng" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f searxng_searxng";
    };
    script = ''
      docker network inspect searxng_searxng || docker network create searxng_searxng
    '';
    partOf = [ "docker-compose-searxng-root.target" ];
    wantedBy = [ "docker-compose-searxng-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-searxng-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
