# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, servicePaths, everythingElsePath, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."sonarr" = {
    image = "lscr.io/linuxserver/sonarr:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    volumes = [
      "${servicePaths.sonarr.configSource}:/config:rw"
      "${everythingElsePath}/arr/tv:/tv:rw"
      "${everythingElsePath}/qbittorrent/downloads:/downloads:rw"
    ];
    ports = [
      "8989:8989/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=sonarr"
      "--network=sonarr_default"
    ];
    labels = {
      "homepage.description" = "For TV shows";
      "homepage.group" = "*arr Stack";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:8989";
      "homepage.icon" = "sonarr";
      "homepage.name" = "Sonarr";
    };
  };
  systemd.services."docker-sonarr" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-sonarr_default.service"
    ];
    requires = [
      "docker-network-sonarr_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      servicePaths.sonarr.configSource
      "${everythingElsePath}/arr/tv"
      "${everythingElsePath}/qbittorrent/downloads/complete"
    ];
  };

  # Networks
  systemd.services."docker-network-sonarr_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f sonarr_default";
    };
    script = ''
      docker network inspect sonarr_default || docker network create sonarr_default
    '';
    partOf = [ "docker-compose-sonarr-root.target" ];
    wantedBy = [ "docker-compose-sonarr-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-sonarr-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
