# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."syncthing" = {
    image = "syncthing/syncthing";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "'Asia/Kolkata'";
    };
    volumes = [
      "/media:/media:rw"
      "/media/HOMELAB_MEDIA/services/syncthing:/var/syncthing/config:rw"
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--hostname=${config.networking.hostName}"
      "--network=host"
    ];
  };
  systemd.services."docker-syncthing" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    unitConfig.RequiresMountsFor = [
      "/media"
      "/media/HOMELAB_MEDIA/services/syncthing"
    ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-syncthing-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
