# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."uptime-kuma" = {
    image = "louislam/uptime-kuma:1";
    volumes = [
      "/media/HOMELAB_MEDIA/services/uptime-kuma:/app/data:rw"
    ];
    ports = [
      "3001:3001/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--dns=1.1.1.1"
      "--dns=100.100.100.100"
      "--dns=127.0.0.1"
      "--dns=8.8.8.8"
      "--network-alias=uptime-kuma"
      "--network=uptime-kuma_default"
    ];
  };
  systemd.services."docker-uptime-kuma" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-uptime-kuma_default.service"
    ];
    requires = [
      "docker-network-uptime-kuma_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/uptime-kuma"
    ];
  };

  # Networks
  systemd.services."docker-network-uptime-kuma_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f uptime-kuma_default";
    };
    script = ''
      docker network inspect uptime-kuma_default || docker network create uptime-kuma_default
    '';
    partOf = [ "docker-compose-uptime-kuma-root.target" ];
    wantedBy = [ "docker-compose-uptime-kuma-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-uptime-kuma-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
