# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 6030;
  internalWebUIPort = 16030;

  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Invidious";
    dockerServiceName = "invidious";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/invidious/companion-cache"
      "${homelabMediaPath}/services/invidious/config/config.yml"
      "${homelabMediaPath}/services/invidious/config/sql"
      "${homelabMediaPath}/services/invidious/docker/init-invidious-db.sh"
      "${homelabMediaPath}/services/invidious/postgres-data"
    ];
    startCommand = "systemctl start docker-invidious-db.service docker-invidious-companion.service docker-invidious.service";
    stopCommand = "systemctl stop docker-compose-invidious-root.target";
    healthEndpoint = "/api/v1/stats";
    waitTimeout = 60;
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets."compose/invidious.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."invidious-companion" = {
    image = "quay.io/invidious/invidious-companion:latest";
    environmentFiles = [
      config.sops.secrets."compose/invidious.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/invidious/companion-cache:/var/tmp/youtubei.js:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--cap-drop=ALL"
      "--network-alias=companion"
      "--network=invidious_default"
      "--security-opt=no-new-privileges:true"
    ];
  };
  systemd.services."docker-invidious-companion" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-invidious_default.service"
    ];
    requires = [
      "docker-network-invidious_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/invidious/companion-cache"
    ];
    partOf = [ "docker-compose-invidious-root.target" ];
    wantedBy = [ "docker-compose-invidious-root.target" ];
  };
  virtualisation.oci-containers.containers."invidious" = {
    image = "quay.io/invidious/invidious:latest-arm64";
    environment = {
      "INVIDIOUS_CONFIG_FILE" = "/config/config.yml";
    };
    volumes = [
      "${homelabMediaPath}/services/invidious/config/config.yml:/config/config.yml:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:3000/tcp"
    ];
    dependsOn = [
      "invidious-db"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=wget -nv --tries=1 --spider http://127.0.0.1:3000/api/v1/stats || exit 1"
      "--health-interval=30s"
      "--health-retries=2"
      "--health-timeout=5s"
      "--network-alias=invidious"
      "--network=invidious_default"
    ];
  };
  systemd.services."docker-invidious" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-invidious_default.service"
    ];
    requires = [
      "docker-network-invidious_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/invidious/config/config.yml"
    ];
    partOf = [ "docker-compose-invidious-root.target" ];
    wantedBy = [ "docker-compose-invidious-root.target" ];
  };
  virtualisation.oci-containers.containers."invidious-db" = {
    image = "docker.io/library/postgres:14";
    environmentFiles = [
      config.sops.secrets."compose/invidious.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/invidious/config/sql:/config/sql:rw"
      "${homelabMediaPath}/services/invidious/docker/init-invidious-db.sh:/docker-entrypoint-initdb.d/init-invidious-db.sh:rw"
      "${homelabMediaPath}/services/invidious/postgres-data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"
      "--network-alias=invidious-db"
      "--network=invidious_default"
    ];
  };
  systemd.services."docker-invidious-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-invidious_default.service"
    ];
    requires = [
      "docker-network-invidious_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/invidious/config/sql"
      "${homelabMediaPath}/services/invidious/docker/init-invidious-db.sh"
      "${homelabMediaPath}/services/invidious/postgres-data"
    ];
    partOf = [ "docker-compose-invidious-root.target" ];
    wantedBy = [ "docker-compose-invidious-root.target" ];
  };

  # Networks
  systemd.services."docker-network-invidious_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f invidious_default";
    };
    script = ''
      docker network inspect invidious_default || docker network create invidious_default
    '';
    partOf = [ "docker-compose-invidious-root.target" ];
    wantedBy = [ "docker-compose-invidious-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-invidious-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
