# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/miniflux.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."miniflux-db" = {
    image = "postgres:15";
    environmentFiles = [
      config.sops.secrets."compose/miniflux.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/miniflux/data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=[\"pg_isready\",\"-U\",\"miniflux\"]"
      "--health-interval=10s"
      "--health-start-period=30s"
      "--network-alias=db"
      "--network=miniflux_default"
    ];
  };
  systemd.services."docker-miniflux-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-miniflux_default.service"
    ];
    requires = [
      "docker-network-miniflux_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/miniflux/data"
    ];
  };
  virtualisation.oci-containers.containers."miniflux" = {
    image = "miniflux/miniflux:latest";
    environmentFiles = [
      config.sops.secrets."compose/miniflux.env".path
    ];
    ports = [
      "3721:8080/tcp"
    ];
    dependsOn = [
      "miniflux-db"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--health-cmd=[\"/usr/bin/miniflux\",\"-healthcheck\",\"auto\"]"
      "--network-alias=miniflux"
      "--network=miniflux_default"
    ];
    labels = {
      "homepage.description" = "RSS Reader";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3721";
      "homepage.icon" = "miniflux";
      "homepage.name" = "Miniflux";
    };
  };
  systemd.services."docker-miniflux" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-miniflux_default.service"
    ];
    requires = [
      "docker-network-miniflux_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-miniflux_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f miniflux_default";
    };
    script = ''
      docker network inspect miniflux_default || docker network create miniflux_default
    '';
    partOf = [ "docker-compose-miniflux-root.target" ];
    wantedBy = [ "docker-compose-miniflux-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-miniflux-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
