# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/miniflux.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."miniflux-db" = {
    image = "postgres:18";
    environmentFiles = [
      config.sops.secrets."compose/miniflux.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/miniflux:/var/lib/postgresql:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=[\"pg_isready\",\"-U\",\"miniflux\"]"
      "--health-interval=10s"
      "--health-start-period=30s"
      "--network-alias=db"
      "--network=miniflux_default"
    ];
  };
  systemd.services."docker-miniflux-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-miniflux_default.service"
    ];
    requires = [
      "docker-network-miniflux_default.service"
    ];
      unitConfig.RequiresMountsFor = [
        "${homelabMediaPath}/services/miniflux"
      ];
  };
  # TODO(2.3.1): miniflux 2.3.0 introduced a broken cross-origin check that rejects
  # logins when the browser sends Origin: null (Firefox/Zen bug, issue #4338).
  # When 2.3.1 is released:
  #   1. Bump image to miniflux/miniflux:2.3.1 (or later)
  #   2. Change port back to "3721:8080/tcp"
  #   3. Remove the services.nginx block below
  virtualisation.oci-containers.containers."miniflux" = {
    image = "miniflux/miniflux:2.3.0";
    environmentFiles = [
      config.sops.secrets."compose/miniflux.env".path
    ];
    ports = [
      "127.0.0.1:8721:8080/tcp"
    ];
    dependsOn = [
      "miniflux-db"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--health-cmd=[\"/usr/bin/miniflux\",\"-healthcheck\",\"auto\"]"
      "--network-alias=miniflux"
      "--network=miniflux_default"
    ];
    labels = {
      "homepage.description" = "RSS Reader";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3721";
      "homepage.icon" = "miniflux";
      "homepage.name" = "Miniflux";
    };
  };
  systemd.services."docker-miniflux" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-miniflux_default.service"
    ];
    requires = [
      "docker-network-miniflux_default.service"
    ];
  };

  # Networks
  systemd.services."docker-network-miniflux_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f miniflux_default";
    };
    script = ''
      docker network inspect miniflux_default || docker network create miniflux_default
    '';
    partOf = [ "docker-compose-miniflux-root.target" ];
    wantedBy = [ "docker-compose-miniflux-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-miniflux-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  # Workaround for miniflux 2.3.0 cross-origin protection bug (issue #4338).
  # Injects Sec-Fetch-Site: same-origin on proxied requests so miniflux's
  # middleware allows the login. Remove this block when upgrading past 2.3.0.
  services.nginx = {
    enable = true;
    virtualHosts."miniflux" = {
      listen = [{ addr = "0.0.0.0"; port = 3721; }];
      locations."/" = {
        proxyPass = "http://127.0.0.1:8721";
        extraConfig = ''
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header Sec-Fetch-Site "same-origin";
        '';
      };
    };
  };

}
