[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-autosuggestions.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "git-repo"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]

[".oh-my-zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/romkatv/powerlevel10k.git"
    refreshPeriod = "168h"
    clone.args = ["--depth", "1"]
#
# [".config/nvim"]
#     type = "git-repo"
#     url = "https://github.com/NvChad/NvChad.git"
#     refreshPeriod = "168h"
#     clone.args = ["--depth", "1"]
