keys:
  - &ritiek 66FF60997B04845FF4C0CB4FEB6FC9F9FC964257
  - &paintball age1m8ge0r6qtghsj88yu8f77660u8z6m2p2uvhg4day4d2c86vtp3kqcf7p72
creation_rules:
  - path_regex: machines/clawsiecats/secrets\.yaml$
    # key_groups:
    #   - pgp:
    #     - *ritiek
    #   - age:
    #     - *paintball
    pgp: *ritiek
    age: *paintball
