keys:
  - &ritiek 66FF60997B04845FF4C0CB4FEB6FC9F9FC964257
  - &mishy age1m8ge0r6qtghsj88yu8f77660u8z6m2p2uvhg4day4d2c86vtp3kqcf7p72
  - &clawsiecats age1ej66fdsu8q3dfdas85zfnw38az79e4tp0hw4sh5587kdzy0l45hsj8cqth
creation_rules:
  - path_regex: machines/secrets\.yaml$
    pgp: *ritiek
  # - path_regex: generators/secrets\.yaml$
  #   pgp: *ritiek
  - path_regex: machines/clawsiecats/secrets\.yaml$
    # key_groups:
    #   - pgp:
    #     - *ritiek
    #   - age:
    #     - *paintball
    pgp: *ritiek
    age: *clawsiecats
    # age: *paintball
