keys:
  - &paintball age1m8ge0r6qtghsj88yu8f77660u8z6m2p2uvhg4day4d2c86vtp3kqcf7p72
  - &clawsiecats age19c9pggn2kah3dj5gmtj6dtwr30d26n82h7yq3ykccljn0lj84ymscnhuyw
creation_rules:
  - path_regex: machines/clawsiecats/secrets\.yaml$
    key_groups:
      - age:
        - *clawsiecats
        - *paintball
