keys:
  - &ritiek 66FF60997B04845FF4C0CB4FEB6FC9F9FC964257
  - &mishy age1ev6fc54zqnsw3fp6c3ue6uzakkk88a2x6ywn9ngelvus4dde29espr2y7a
  - &pilab age18z96a5v4ugj5lmwgs0xfn4ernq8s44mszf5amp6qxdgyzrg7wusqkhuy8u
  - &clawsiecats age1ej66fdsu8q3dfdas85zfnw38az79e4tp0hw4sh5587kdzy0l45hsj8cqth
  - &keyberry age16ta3nkg3jrruu27tqux4uswj6ha2pd64myecp4a34rxyqlgnd9tsxj95w5
  - &stashy age13fpx2errrwgxt4fsxagtvf7z77srxw0wvwlekuz4qgez7wtz4ccslvsgmv
  - &zerostash age1xy3tu6wccq0jf3epxefeh6t5xu2lvudkcu56tzdrgprmvxfm7y2qpyuqwa
  - &mangoshake age17r6ljsa6sg0706cq7j3gfevnk3k8knlvz5vppelaj996q5gnf4jqzyxk28

creation_rules:
  - path_regex: machines/secrets\.yaml$
    pgp: *ritiek

  - path_regex: machines/mishy/home/secrets\.yaml$
    pgp: *ritiek
    age: *mishy

  - path_regex: machines/pilab/secrets\.yaml$
    pgp: *ritiek
    age: *pilab
  - path_regex: machines/pilab/home/secrets\.yaml$
    pgp: *ritiek
    age: *pilab
  - path_regex: machines/pilab/compose/.*/stack\.env$
    pgp: *ritiek
    age: *pilab

  - path_regex: machines/clawsiecats/secrets\.yaml$
    # key_groups:
    #   - pgp:
    #     - *ritiek
    #   - age:
    #     - *paintball
    pgp: *ritiek
    age: *clawsiecats
    # age: *mishy

  - path_regex: machines/keyberry/secrets\.yaml$
    pgp: *ritiek
    age: *keyberry
  - path_regex: machines/keyberry/home/secrets\.yaml$
    pgp: *ritiek
    age: *keyberry

  - path_regex: machines/stashy/secrets\.yaml$
    pgp: *ritiek
    age: *stashy
  - path_regex: machines/stashy/home/secrets\.yaml$
    pgp: *ritiek
    age: *stashy

  - path_regex: machines/zerostash/secrets\.yaml$
    pgp: *ritiek
    age: *zerostash
  - path_regex: machines/zerostash/home/secrets\.yaml$
    pgp: *ritiek
    age: *zerostash

  - path_regex: machines/mangoshake/secrets\.yaml$
    pgp: *ritiek
    age: *mangoshake
