keys:
  - &ritiek 66FF60997B04845FF4C0CB4FEB6FC9F9FC964257
  - &mishy age13qqharyg32umzahtpnnm8f3kazfd6klm9p7rz5y0rjmmh893vapqg90u69
  - &clawsiecats age1ej66fdsu8q3dfdas85zfnw38az79e4tp0hw4sh5587kdzy0l45hsj8cqth
  - &nixypi age1d9a7lvrcyz5pnaezcc90n8wc3qq7tx3vgqa2ccdhqtrmrmd20cjsh0ndu8
  - &stashy age13fpx2errrwgxt4fsxagtvf7z77srxw0wvwlekuz4qgez7wtz4ccslvsgmv
  - &mangoshake age17r6ljsa6sg0706cq7j3gfevnk3k8knlvz5vppelaj996q5gnf4jqzyxk28
creation_rules:
  - path_regex: machines/secrets\.yaml$
    pgp: *ritiek
  - path_regex: machines/mishy/home/secrets\.yaml$
    pgp: *ritiek
    age: *mishy
  # - path_regex: generators/secrets\.yaml$
  #   pgp: *ritiek
  - path_regex: machines/clawsiecats/secrets\.yaml$
    # key_groups:
    #   - pgp:
    #     - *ritiek
    #   - age:
    #     - *paintball
    pgp: *ritiek
    age: *clawsiecats
    # age: *mishy
  - path_regex: machines/nixypi/secrets\.yaml$
    pgp: *ritiek
    age: *nixypi
  - path_regex: machines/stashy/secrets\.yaml$
    pgp: *ritiek
    age: *stashy
  - path_regex: machines/mangoshake/secrets\.yaml$
    pgp: *ritiek
    age: *mangoshake
