# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  # Configuration
  webUIPort = 3456;
  internalWebUIPort = 13456;

  # Import shared lazy-loading utilities
  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  # Generate lazy-loading services
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Meridian";
    dockerServiceName = "meridian-proxy";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    refreshInterval = 3;
    silent = true;
    requiredMounts = [
      "${homelabMediaPath}/services/meridian/claude-auth"
    ];
    rootTarget = "docker-compose-meridian-root.target";
    startCommand = "systemctl start docker-compose-meridian-root.target";
    stopCommand = "systemctl stop docker-compose-meridian-root.target";
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets."compose/meridian.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."meridian-init" = {
    image = "busybox";
    volumes = [
      "${homelabMediaPath}/services/meridian/claude-auth:/home/claude/.claude:rw"
    ];
    user = "root";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--entrypoint=[\"sh\", \"-c\", \"chown -R 1000:1000 /home/claude/.claude\"]"
      "--network-alias=init"
      "--network=meridian_default"
    ];
  };
  systemd.services."docker-meridian-init" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-meridian_default.service"
    ];
    requires = [
      "docker-network-meridian_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/meridian/claude-auth"
    ];
  };
  virtualisation.oci-containers.containers."meridian-proxy" = {
    image = "ghcr.io/rynfar/meridian:latest";
    environmentFiles = [
      config.sops.secrets."compose/meridian.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/meridian/claude-auth:/home/claude/.claude:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:3456/tcp"  # Internal port only
    ];
    dependsOn = [
      "meridian-init"
    ];
    user = "claude";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=proxy"
      "--network=meridian_default"
    ];
  };
  systemd.services."docker-meridian-proxy" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-meridian_default.service"
    ];
    requires = [
      "docker-network-meridian_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/meridian/claude-auth"
    ];
    # Bind to root target
    partOf = [ "docker-compose-meridian-root.target" ];
    wantedBy = [ "docker-compose-meridian-root.target" ];
  };

  # Networks
  systemd.services."docker-network-meridian_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f meridian_default";
    };
    script = ''
      docker network inspect meridian_default || docker network create meridian_default
    '';
    partOf = [ "docker-compose-meridian-root.target" ];
    wantedBy = [ "docker-compose-meridian-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-meridian-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  }
]
