# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets = {
    "compose/backvault.env" = {
      sopsFile = ./stack.env;
      format = "dotenv";
    };
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."backvault" = {
    # TODO: Use the upstream image from `mvflc/backvault` when it supports ARM64.
    image = "ghcr.io/ritiek/backvault";
    environmentFiles = [
      config.sops.secrets."compose/backvault.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/backvault/backups:/app/backups:rw"
      "${homelabMediaPath}/services/backvault/db:/app/db:rw"
    ];
    # ports = [
    #   "8080:8080/tcp"
    # ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=backvault"
      "--network=backvault_default"
    ];
  };
  systemd.services."docker-backvault" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-backvault_default.service"
    ];
    requires = [
      "docker-network-backvault_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/backvault/backups"
      "${homelabMediaPath}/services/backvault/db"
    ];
  };

  # Networks
  systemd.services."docker-network-backvault_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f backvault_default";
    };
    script = ''
      docker network inspect backvault_default || docker network create backvault_default
    '';
    partOf = [ "docker-compose-backvault-root.target" ];
    wantedBy = [ "docker-compose-backvault-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-backvault-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
