# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/atuin.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."atuin" = {
    image = "ghcr.io/atuinsh/atuin:8a010fe-aarch64";
    environmentFiles = [
      config.sops.secrets."compose/atuin.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/atuin/config:/config:rw"
    ];
    ports = [
      "7235:8888/tcp"
    ];
    cmd = [ "server" "start" ];
    dependsOn = [
      "atuin-db"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=atuin"
      "--network=atuin_default"
    ];
    labels = {
      "homepage.description" = "Shell history";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:7235";
      "homepage.icon" = "atuin";
      "homepage.name" = "Atuin";
    };
  };
  systemd.services."docker-atuin" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-atuin_default.service"
    ];
    requires = [
      "docker-network-atuin_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/atuin/config"
    ];
  };
  virtualisation.oci-containers.containers."atuin-db" = {
    image = "postgres:14";
    environmentFiles = [
      config.sops.secrets."compose/atuin.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/atuin/postgres-data:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=db"
      "--network=atuin_default"
    ];
  };
  systemd.services."docker-atuin-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-atuin_default.service"
    ];
    requires = [
      "docker-network-atuin_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/atuin/postgres-data"
    ];
  };

  # Networks
  systemd.services."docker-network-atuin_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f atuin_default";
    };
    script = ''
      docker network inspect atuin_default || docker network create atuin_default
    '';
    partOf = [ "docker-compose-atuin-root.target" ];
    wantedBy = [ "docker-compose-atuin-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-atuin-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
