# OpenWrt SD-card image for switchwrt (Radxa Cubie A5E, 1 GB variant),
# built declaratively with ayles/nix-openwrt.  aarch64-linux only -- the
# OpenWrt buildroot is compiled natively, so run `nix build
# /etc/nixos#switchwrt-sd` on an aarch64 host (e.g. alcove).
#
# The OpenWrt source is pinned to our fork branch, which carries all of the
# board support in-tree: A523/A527 CPU DVFS, thermal, PCIe/IOMMU and WiFi
# patches (target/linux/sunxi/patches-6.18/), U-Boot DRAM-timing + earlycon
# changes (package/boot/uboot-sunxi/), the radxa_cubie-a5e device
# definition, TF-A/ATF support and the out-of-tree AIC8800D80 SDIO WiFi
# package.  nix-openwrt's `patches` attribute can only drop patch files
# into OpenWrt's quilt patch dirs, so it cannot express device/package
# tree content -- hence a fork pin instead of upstream + patch list.
#
# Two overrides on nix-openwrt's hardcoded fixes:
# - tools/fakeroot/patches/900-einval.patch (libfakeroot: forgive EINVAL
#   inside user namespaces).  Our tree already ships the same fix as
#   400-userns-chown-einval.patch, so ayles' copy would find its hunks
#   already applied and fail the quilt push; replace it with a no-op patch.
# - package/base-files/Makefile: full-file replacement.  A source tarball
#   has no .git, so scripts/getver.sh yields REVISION=unknown and
#   COMMITCOUNT=700101.00001, and base-files then emits the apk package
#   version "700101.00001~unknown" -- which apk rejects (the suffix after
#   '~' must contain digits).  When REVISION=unknown, fall back to a bare
#   $(PKG_RELEASE).  Full-file copy instead of a patches/ drop because
#   base-files has no package source, so its quilt patch phase never runs.
#
# Go on an aarch64 build host: adguardhome is the first Go package in this
# config, and the packages feed builds host Go from a bootstrap chain that
# starts by compiling go1.4 -- whose Makefile hard-rejects linux/arm64
# ("go-bootstrap cannot be installed on linux/arm64"), and it would mean
# compiling Go four times over anyway.  Instead point the feed's
# GOLANG_EXTERNAL_BOOTSTRAP_ROOT at nixpkgs' Go (extraBuildInputs puts it
# in both FHS build sandboxes; >= go1.25 satisfies Go 1.27's bootstrap
# minimum) and disable GOLANG_BUILD_BOOTSTRAP so host Go 1.27 builds
# straight from source against it.  nixpkgs' go must also be on PATH for
# ayles' Go-module prefetch of Go package sources.
#
# To bump the OpenWrt pin, update `src.rev`/`src.hash` (prefetch with
# `nix store prefetch-file --unpack --json
# https://codeload.github.com/ritiek/openwrt/tar.gz/<rev>`), then set
# `downloadsHash = pkgs.lib.fakeHash;`, build once, and pin the `got:`
# hash nix reports.
{
  inputs,
  pkgs,
}:
let
  # Vendored LuCI app for the netbird client (looong-cat/luci-app-netbird;
  # not in any official feed, targets apk-era OpenWrt).  Pinned by rev and
  # copied into an in-tree package dir via the patches attribute below.
  # Its EXTRA_DEPENDS (netbird, rpcd, luci-base, conntrack) are metadata
  # only -- conntrack is therefore selected explicitly in config.seed.
  netbirdApp = pkgs.fetchFromGitHub {
    owner = "looong-cat";
    repo = "luci-app-netbird";
    rev = "164f2cf1b6c6de7dcf56f5059a21a7abe3acac62";
    hash = "sha256-2zAQEbykUKcu16+49YOt6RdCJfAqcKqG7xP3A2wUwxI=";
  };  netbirdAppFiles = [
    "LICENSE"
    "Makefile"
    "htdocs/luci-static/resources/view/netbird/dom-helpers.js"
    "htdocs/luci-static/resources/view/netbird/logs.js"
    "htdocs/luci-static/resources/view/netbird/netbird.css"
    "htdocs/luci-static/resources/view/netbird/overview.js"
    "htdocs/luci-static/resources/view/netbird/settings.js"
    "htdocs/luci-static/resources/view/netbird/setup.js"
    "htdocs/luci-static/resources/view/netbird/status.js"
    "htdocs/luci-static/resources/view/netbird/versions.js"
    "po/templates/netbird.pot"
    "po/zh_Hans/netbird.po"
    "root/etc/config/netbird"
    "root/etc/config/netbird_bin"
    "root/etc/init.d/luci-netbird-watchdog"
    "root/etc/init.d/netbird-settings"
    "root/etc/uci-defaults/99-luci-app-netbird"
    "root/usr/share/luci-app-netbird/defaults/netbird.uci"
    "root/usr/share/luci/menu.d/luci-app-netbird.json"
    "root/usr/share/netbird/netbird-autoreconnect.sh"
    "root/usr/share/rpcd/acl.d/luci-app-netbird.json"
    "root/usr/share/rpcd/ucode/lib/envelope.uc"
    "root/usr/share/rpcd/ucode/lib/netbird_cli.uc"
    "root/usr/share/rpcd/ucode/lib/paths.uc"
    "root/usr/share/rpcd/ucode/lib/sanitize.uc"
    "root/usr/share/rpcd/ucode/lib/shell.uc"
    "root/usr/share/rpcd/ucode/lib/state.uc"
    "root/usr/share/rpcd/ucode/netbird.uc"
  ];

  # Vendored LuCI theme (jerrykuku/luci-theme-argon, the ucode-era master
  # layout; not in any official feed).  Every file in the repo root is part
  # of the package (htdocs, ucode templates, uci-defaults, rpcd helper), so
  # the file list is generated by walking the fetched source at eval time.
  # Theme activation happens through the package's own
  # root/etc/uci-defaults/30_luci-theme-argon; the wget-any dependency
  # resolves because uclient-fetch (base system) PROVIDES @wget-any.  Exec
  # bits lost to the patches mechanism's 644 installs are restored by
  # files/etc/uci-defaults/98-luci-apps-setup at first boot.
  argonApp = pkgs.fetchFromGitHub {
    owner = "jerrykuku";
    repo = "luci-theme-argon";
    rev = "ddefe5f05ca334dba10d2d65d25ebf14e986ee88";
    hash = "sha256-DzyrTzHEfBFaRCqBZaIg1wmqKIbiFHyh7Hey9HiuP78=";
  };
  # Shared recursive-walk helper, reused for every vendored package below
  # where "the whole repo is the package source" (no hand-curated file
  # list needed, unlike luci-app-netbird's). Symlinked directories (e.g.
  # po/zh_Hans -> po/zh_CN, a common locale-alias pattern) report type
  # "symlink" from readDir without resolving -- treating those as plain
  # files broke the build outright ("install: omitting directory") since
  # `install -Dm644` refuses to copy a directory. Detect that case by
  # attempting readDir on the target and recursing if it succeeds.
  walkDir = prefix: dir:
    builtins.concatMap
      (name:
        let
          rel = if prefix == "" then name else "${prefix}/${name}";
          type = (builtins.readDir dir)."${name}";
          isDir = type == "directory" || (type == "symlink" &&
            (builtins.tryEval (builtins.readDir (dir + "/${name}"))).success);
        in
        if isDir
        then walkDir rel (dir + "/${name}")
        else [ rel ])
      (builtins.attrNames (builtins.readDir dir));
  argonFiles = walkDir "" argonApp;

  # Portable-router LuCI extras (all vendored, none in any official feed):
  # bandwidth-adjacent status widgets + a speed test + a LuCI-UI MAC
  # randomizer (we already built our own boot-time MAC randomization --
  # files/etc/init.d/randomize-wwan-mac -- this is separate/redundant
  # prior art the user asked for anyway, see the LuCI-addons discussion).
  internetDetectorSrc = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-internet-detector";
    rev = "a4ac581a57121de0c6e8628028eaaea36a524576";
    hash = "sha256-LmBjlyxwfFjHL33JnvZxRmtpEZD/7+haiSNKa6mSGBY=";
  };
  # Monorepo: only vendor the core daemon + the LuCI UI, skip the optional
  # notification modules (mod-email/mod-telegram/mod-modem-restart) -- not
  # needed right now, can be added the same way later if wanted.
  internetDetectorCoreFiles = walkDir "" (internetDetectorSrc + "/internet-detector");
  internetDetectorLuciFiles = walkDir "" (internetDetectorSrc + "/luci-app-internet-detector");

  tempStatusApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-temp-status";
    rev = "7c47517c1cd3d1ccf52eda9237279a45d5884e34";
    hash = "sha256-ZL5OuT67Qy7t/y5fnuQKH8wpWFrodOgw+ZiMLKJK97Q=";
  };
  tempStatusFiles = walkDir "" tempStatusApp;

  cpuStatusApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-cpu-status";
    rev = "d25a968ba844fc9050d4de312f81eb2a495113a2";
    hash = "sha256-eP93dJwq11huPt5wZiTxkRBv6EqAClb15fBCt7A5vTM=";
  };
  cpuStatusFiles = walkDir "" cpuStatusApp;

  # PKG_UNPACK in this package's Makefile directly execs .prepare.sh by
  # path, but the patches mechanism below installs every file at mode 644,
  # so the buildroot's unpack step dies with "Error 126" mid-compile --
  # where the usual boot-time chmod-fixup pattern cannot reach it. Missed
  # on the first vendoring pass and it broke a multi-hour rebuild. Fixed
  # with a locally patched Makefile that invokes it via `sh`; see
  # ./patches/luci-app-netspeedtest-Makefile for the full write-up.
  netspeedtestApp = pkgs.fetchFromGitHub {
    owner = "muink";
    repo = "luci-app-netspeedtest";
    rev = "11147316267a2046ca6457f1b695e2efdf476891";
    hash = "sha256-6B9764jSNdO2wPuzyw/P1lUeFPFRG3IEiIvgzUWmYrM=";
  };
  netspeedtestFiles =
    builtins.filter (f: f != "Makefile") (walkDir "" netspeedtestApp);

  # Repo dir is "luci-app-log" but the package's own PKG_NAME is
  # luci-app-log-viewer -- vendor path below uses the real package name.
  logViewerApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-log";
    rev = "4d5601b7f6c639550d5a257b402b4ce73a06cfbf";
    hash = "sha256-T5UZ2ogAWT/kLbj50z/lsYiUIr9WouRhju/ftKVwhOA=";
  };
  logViewerFiles = walkDir "" logViewerApp;

  interfacesStatsApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-interfaces-statistics";
    rev = "a53851f3beade7360e397e6f580855c4a39dd300";
    hash = "sha256-mAzv5p3Hd3v6E/5rlV2rrwV80K4KbyLCqfC/yAcaMQg=";
  };
  interfacesStatsFiles = walkDir "" interfacesStatsApp;

  ipinfoApp = pkgs.fetchFromGitHub {
    owner = "animegasan";
    repo = "luci-app-ipinfo";
    rev = "fb9948abe3bfe658c8c47d759b3b8ae87bb1d5d1";
    hash = "sha256-k9jjNVjTRa3V9xSZ2zIaq+2Xn/Tp9Tv56mjAp1660To=";
  };
  ipinfoFiles = walkDir "" ipinfoApp;

  openwrt = inputs.nix-openwrt.lib.build {
    inherit pkgs;
    src = pkgs.fetchFromGitHub {
      owner = "ritiek";
      repo = "openwrt";
      rev = "ad633d4568c054fcf0e6ed89b48e4d36a7651c7f";
      hash = "sha256-P1cWrcC09OPyvcVd8+ygZU0jmRTKHTgqRaclXoSI3bI=";
    };
    config = ./config.seed;
    target = "sunxi";
    subtarget = "cortexa55";
    profile = "radxa_cubie-a5e";
    # Pinned by the bootstrap build (set to pkgs.lib.fakeHash, build once,
    # and replace with the `got:` hash nix reports).
    downloadsHash = "sha256-ikSScTd9tmOLQ2IlNDONYzt8XNYmwmhFOwUTNWpTM7o=";

    # See the "Go on an aarch64 build host" note above.
    extraBuildInputs = [ pkgs.go ];
    extraConfig = ''
      CONFIG_GOLANG_BUILD_BOOTSTRAP=n
      CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT=${pkgs.go}/share/go
    '';

    patches = {
      "tools/fakeroot/patches/900-einval.patch" =
        ./patches/900-einval-neutralized.patch;
      "package/base-files/Makefile" = ./patches/base-files-Makefile;
      # Baked into the rootfs by the tree build (buildroot overlays the
      # tree-root files/ directory into every image it assembles).
      "files/etc/uci-defaults/97-wifi-ap" = ./files/etc/uci-defaults/97-wifi-ap;
      "files/etc/uci-defaults/98-allow-ssh-wan" =
        ./files/etc/uci-defaults/98-allow-ssh-wan;

      # Key-only SSH: fleet authorized_keys baked in, password auth off
      # (root's password is not baked in either -- it arrives at runtime as
      # a hash via switchwrt-apply-secrets; see 92-dropbear-harden).
      "files/etc/dropbear/authorized_keys" =
        ./files/etc/dropbear/authorized_keys;
      "files/etc/uci-defaults/92-dropbear-harden" =
        ./files/etc/uci-defaults/92-dropbear-harden;
      "files/etc/uci-defaults/99-switchboard-lan-ip" =
        ./files/etc/uci-defaults/99-switchboard-lan-ip;

      # AdGuardHome DNS layer (see the comments in files/etc/adguardhome/
      # and the 95-adguardhome-dns uci-defaults script for the full wiring).
      # The uci-defaults script below exists because every file here is
      # installed with mode 644, so exec bits have to be restored on boot.
      "files/etc/adguardhome/adguardhome.yaml" =
        ./files/etc/adguardhome/adguardhome.yaml;
      "files/etc/uci-defaults/95-adguardhome-dns" =
        ./files/etc/uci-defaults/95-adguardhome-dns;
      "files/www/home/index.html" = ./files/www/home/index.html;

      # General dnsmasq/DHCP tweak, unrelated to the AdGuardHome layer above:
      # allocate leases sequentially from the lowest free address.
      "files/etc/uci-defaults/95-dhcp-sequential-ip" =
        ./files/etc/uci-defaults/95-dhcp-sequential-ip;

      # VPN mesh layer: tailscale + netbird (see the *-login init scripts
      # and 94-vpn-setup for the wiring).  No keys here: the image is
      # secret-free and the authkey/setupkey arrive at runtime via
      # deploy-secrets.sh -> switchwrt-apply-secrets.
      # 96-tailscale-luci-seed declaratively seeds the LuCI app's UCI
      # defaults so its boot-time `tailscale set` keeps the first-boot
      # flags (exit node advertisement, DNS off).
      "files/etc/sysctl.d/90-tailscale.conf" =
        ./files/etc/sysctl.d/90-tailscale.conf;
      # Keeps directly-connected subnets winning over the subnet routes
      # tailnet peers advertise (pilab advertises 192.168.2.0/24, which is
      # also our own uplink subnet at home) -- without this, replies to
      # same-wire hosts leak into the tunnel and WAN-side LuCI/SSH break.
      "files/etc/hotplug.d/iface/25-connected-subnet-priority" =
        ./files/etc/hotplug.d/iface/25-connected-subnet-priority;
      # tailscaled (S80) races DNS at boot: its one login attempt fires
      # before AdGuardHome is listening, stalls, and is never retried, so
      # the node sits in NoState. Re-kick it once an uplink is really up.
      "files/etc/hotplug.d/iface/26-tailscale-kick" =
        ./files/etc/hotplug.d/iface/26-tailscale-kick;
      "files/etc/init.d/tailscale-login" =
        ./files/etc/init.d/tailscale-login;
      "files/etc/init.d/netbird-login" =
        ./files/etc/init.d/netbird-login;
      "files/etc/uci-defaults/94-vpn-setup" =
        ./files/etc/uci-defaults/94-vpn-setup;
      "files/etc/uci-defaults/96-tailscale-luci-seed" =
        ./files/etc/uci-defaults/96-tailscale-luci-seed;

      # Runtime secret delivery. The image ships no secrets at all (see
      # .sops.yaml); machines/switchwrt/deploy-secrets.sh decrypts
      # secrets.yaml on the operator's machine and pipes the values into
      # this helper over ssh, which writes the VPN enrolment keys, the AP
      # passphrase and root's password hash, then enables what they gate.
      "files/usr/sbin/switchwrt-apply-secrets" =
        ./files/usr/sbin/switchwrt-apply-secrets;

      # Machine identity (hostname -> switchwrt; also the name tailscale
      # registers this node under on first boot).
      "files/etc/uci-defaults/99-switchwrt-hostname" =
        ./files/etc/uci-defaults/99-switchwrt-hostname;

      # Fleet-wide timezone standard (every NixOS machine sets
      # time.timeZone = "Asia/Kolkata"); pin this OpenWrt box the same way.
      "files/etc/uci-defaults/99-switchwrt-timezone" =
        ./files/etc/uci-defaults/99-switchwrt-timezone;

      # Move the tailscale LuCI app from the VPN tab next to NetBird under
      # Services (tree files/ overrides the feed package's menu.d entry).
      "files/usr/share/luci/menu.d/luci-app-tailscale-community.json" =
        ./files/usr/share/luci/menu.d/luci-app-tailscale-community.json;

      # Exec bits for the vendored packages' executable files (see the
      # comment in the script).
      "files/etc/uci-defaults/98-luci-apps-setup" =
        ./files/etc/uci-defaults/98-luci-apps-setup;

      # Trusted firewall zone for tailscale0 (see the comment in the
      # script; without it the dashboards are unreachable over tailscale).
      "files/etc/uci-defaults/98-tailscale-fw-zone" =
        ./files/etc/uci-defaults/98-tailscale-fw-zone;

      # WISP uplink: USB WiFi dongle joins the ONT's own SSID as a second
      # WAN path, with mwan3 handling automatic failover (eth1 preferred)
      # and per-device pinning via LuCI. See the comments in both scripts.
      "files/etc/uci-defaults/97-wwan-uplink" =
        ./files/etc/uci-defaults/97-wwan-uplink;
      "files/etc/uci-defaults/97-usbtether-uplink" =
        ./files/etc/uci-defaults/97-usbtether-uplink;
      "files/etc/uci-defaults/98-mwan3-setup" =
        ./files/etc/uci-defaults/98-mwan3-setup;

      # Portable-router extras: MAC randomization for the WISP dongle
      # (real init.d script, runs every boot, not a uci-defaults one-shot)
      # and a software RTC substitute (no hardware RTC on this board).
      "files/etc/init.d/randomize-wwan-mac" =
        ./files/etc/init.d/randomize-wwan-mac;
      "files/etc/init.d/faketime" =
        ./files/etc/init.d/faketime;
      "files/etc/uci-defaults/93-portable-router-setup" =
        ./files/etc/uci-defaults/93-portable-router-setup;
    }
    # Vendor the netbird LuCI app into the build tree as an in-tree
    # package; the buildroot then packages it with correct file modes
    # (unlike tree files/, which land mode 644).
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-netbird/${f}";
        value = "${netbirdApp}/luci-app-netbird/${f}";
      })
      netbirdAppFiles)
    # Portable-router LuCI extras: internet-detector's monorepo splits into
    # two packages we actually want (core daemon + LuCI UI); everything
    # else below is "whole repo is the package source", same as argon.
    // builtins.listToAttrs (map
      (f: {
        name = "package/internet-detector/${f}";
        value = "${internetDetectorSrc}/internet-detector/${f}";
      })
      internetDetectorCoreFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-internet-detector/${f}";
        value = "${internetDetectorSrc}/luci-app-internet-detector/${f}";
      })
      internetDetectorLuciFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-temp-status/${f}";
        value = "${tempStatusApp}/${f}";
      })
      tempStatusFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-cpu-status/${f}";
        value = "${cpuStatusApp}/${f}";
      })
      cpuStatusFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-netspeedtest/${f}";
        value = "${netspeedtestApp}/${f}";
      })
      netspeedtestFiles)
    # Locally patched Makefile (sh-invoked .prepare.sh) for the package
    # above.
    // {
      "package/luci-app-netspeedtest/Makefile" =
        ./patches/luci-app-netspeedtest-Makefile;
    }
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-log-viewer/${f}";
        value = "${logViewerApp}/${f}";
      })
      logViewerFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-interfaces-statistics/${f}";
        value = "${interfacesStatsApp}/${f}";
      })
      interfacesStatsFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-ipinfo/${f}";
        value = "${ipinfoApp}/${f}";
      })
      ipinfoFiles)
    # Same for the argon theme (whole repo is the package source).
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-theme-argon/${f}";
        value = "${argonApp}/${f}";
      })
      argonFiles);
  };
in
let
  imageDrv = openwrt.mkImage {
    # Package set for the ImageBuilder assembly (`make image PACKAGES=...`).
    # `config.seed` above compiles these during the full build, but the
    # ImageBuilder does not inherit the tree config's package selections, so
    # everything beyond the profile defaults must be listed here as well.
    packages = [
      "kmod-aic8800-sdio"
      "aic8800-sdio-firmware"
      "-wpad-basic-mbedtls"
      "wpad-mbedtls"
      "iw-full"
      "tcpdump"
      "ethtool"
      "kmod-sdhci"
      "luci"
      "luci-ssl"
      "adguardhome"
      "luci-app-adguardhome"
      "tailscale"
      "kmod-tun"
      "luci-app-tailscale-community"
      "netbird"
      "luci-app-netbird"
      "conntrack"
      "luci-theme-argon"
      "kmod-wireguard"
      "kmod-rtl8xxxu"
      "mwan3"
      "luci-app-mwan3"
      "nlbwmon"
      "luci-app-nlbwmon"
      "luci-app-sqm"
      "luci-app-samba4"
      "samba4-server"
      "internet-detector"
      "luci-app-internet-detector"
      "luci-app-temp-status"
      "luci-app-cpu-status"
      "luci-app-netspeedtest"
      "luci-app-log-viewer"
      "luci-app-interfaces-statistics"
      "luci-app-ipinfo"
      "luci-app-filebrowser"
      "travelmate"
      "luci-lib-uqr"
      "luci-app-travelmate"
      "vnstat2"
      "vnstati2"
      "luci-app-vnstat2"
      "ttyd"
      "luci-app-ttyd"
      "natmap"
      "luci-app-natmap"
      "chrony"
      "luci-app-chrony"
      "miniupnpd"
      "rpcd-mod-ucode"
      "luci-app-upnp"
      "kmod-usb-net"
      "kmod-usb-net-rndis"
      "kmod-usb-net-cdc-ether"
      "kmod-usb-net-ipheth"
    ];
    files = ./files;
  };

  # mkImage expects an ImageBuilder tarball under bin/targets/..., but the
  # full build only runs `make world`, which never produces one -- so
  # ayles' `tar xf .../openwrt-imagebuilder-*.tar.*` fails outright.  The
  # full build already assembled the complete image for our profile
  # (config.seed selects every package, and files/ is baked in via the
  # patches attribute), so replace the phase with a plain copy of the
  # artifacts out of the full build output.  If ayles/nix-openwrt ever
  # grows a real ImageBuilder stage, this override can be dropped.
  tarLine =
    pkgs.lib.findFirst
      (pkgs.lib.strings.hasInfix "tar xf")
      ""
      (pkgs.lib.strings.splitString "\n" imageDrv.buildPhase);
  buildTree = builtins.head (builtins.match "tar xf \"([^\"]+)\".*" tarLine);

  # The tar line is spliced out with builtins.replaceStrings over the
  # original buildPhase -- NOT swapped for a hand-written phase --
  # because replaceStrings keeps the input string's context while
  # writing a fresh phase (or builtins.match) would drop it: without the
  # context the full-build derivation is not a real dependency, nix
  # never builds it, and the store path below is absent at build time.
  copyPhase = ''
    set -euo pipefail
    mkdir -p "$out"
    cp -t "$out" \
      ${buildTree}/bin/targets/sunxi/cortexa55/*.img.gz \
      ${buildTree}/bin/targets/sunxi/cortexa55/*.manifest \
      ${buildTree}/bin/targets/sunxi/cortexa55/sha256sums
    cd "$out"
    for f in *-squashfs-sdcard.img.gz; do
      ln -sf "$f" sdcard.img.gz
    done
    # Everything ayles' phase does after the tar line (cd into the
    # ImageBuilder, `make image`, artifact collection) is ImageBuilder
    # machinery we are replacing wholesale -- skip it.
    exit 0
  '';
in
pkgs.lib.overrideDerivation imageDrv (old: {
  # Name the artifact after the machine, not the distro
  # (openwrt-image-radxa_cubie-a5e-<rev> -> switchwrt-image-...).
  name = builtins.replaceStrings
    [ "openwrt-image-" ]
    [ "switchwrt-image-" ]
    old.name;
  buildPhase = builtins.replaceStrings [ tarLine ] [ copyPhase ] imageDrv.buildPhase;
})
