# OpenWrt SD-card image for switchwrt (Radxa Cubie A5E, 1 GB variant),
# built declaratively with ayles/nix-openwrt.  aarch64-linux only -- the
# OpenWrt buildroot is compiled natively, so run `nix build
# /etc/nixos#switchwrt-sd` on an aarch64 host (e.g. alcove).
#
# The OpenWrt source is pinned to our fork branch, which carries all of the
# board support in-tree: A523/A527 CPU DVFS, thermal, PCIe/IOMMU and WiFi
# patches (target/linux/sunxi/patches-6.18/), U-Boot DRAM-timing + earlycon
# changes (package/boot/uboot-sunxi/), the radxa_cubie-a5e device
# definition, TF-A/ATF support and the out-of-tree AIC8800D80 SDIO WiFi
# package.  nix-openwrt's `patches` attribute can only drop patch files
# into OpenWrt's quilt patch dirs, so it cannot express device/package
# tree content -- hence a fork pin instead of upstream + patch list.
#
# Two overrides on nix-openwrt's hardcoded fixes:
# - tools/fakeroot/patches/900-einval.patch (libfakeroot: forgive EINVAL
#   inside user namespaces).  Our tree already ships the same fix as
#   400-userns-chown-einval.patch, so ayles' copy would find its hunks
#   already applied and fail the quilt push; replace it with a no-op patch.
# - package/base-files/Makefile: full-file replacement.  A source tarball
#   has no .git, so scripts/getver.sh yields REVISION=unknown and
#   COMMITCOUNT=700101.00001, and base-files then emits the apk package
#   version "700101.00001~unknown" -- which apk rejects (the suffix after
#   '~' must contain digits).  When REVISION=unknown, fall back to a bare
#   $(PKG_RELEASE).  Full-file copy instead of a patches/ drop because
#   base-files has no package source, so its quilt patch phase never runs.
#
# Go on an aarch64 build host: adguardhome is the first Go package in this
# config, and the packages feed builds host Go from a bootstrap chain that
# starts by compiling go1.4 -- whose Makefile hard-rejects linux/arm64
# ("go-bootstrap cannot be installed on linux/arm64"), and it would mean
# compiling Go four times over anyway.  Instead point the feed's
# GOLANG_EXTERNAL_BOOTSTRAP_ROOT at nixpkgs' Go (extraBuildInputs puts it
# in both FHS build sandboxes; >= go1.25 satisfies Go 1.27's bootstrap
# minimum) and disable GOLANG_BUILD_BOOTSTRAP so host Go 1.27 builds
# straight from source against it.  nixpkgs' go must also be on PATH for
# ayles' Go-module prefetch of Go package sources.
#
# To bump the OpenWrt pin, update `src.rev`/`src.hash` (prefetch with
# `nix store prefetch-file --unpack --json
# https://codeload.github.com/ritiek/openwrt/tar.gz/<rev>`), then set
# `downloadsHash = pkgs.lib.fakeHash;`, build once, and pin the `got:`
# hash nix reports.
{
  inputs,
  pkgs,
}:
let
  # Vendored LuCI app for the netbird client (looong-cat/luci-app-netbird;
  # not in any official feed, targets apk-era OpenWrt).  Pinned by rev and
  # copied into an in-tree package dir via the patches attribute below.
  # Its EXTRA_DEPENDS (netbird, rpcd, luci-base, conntrack) are metadata
  # only -- conntrack is therefore selected explicitly in config.seed.
  netbirdApp = pkgs.fetchFromGitHub {
    owner = "looong-cat";
    repo = "luci-app-netbird";
    rev = "164f2cf1b6c6de7dcf56f5059a21a7abe3acac62";
    hash = "sha256-2zAQEbykUKcu16+49YOt6RdCJfAqcKqG7xP3A2wUwxI=";
  };  netbirdAppFiles = [
    "LICENSE"
    "Makefile"
    "htdocs/luci-static/resources/view/netbird/dom-helpers.js"
    "htdocs/luci-static/resources/view/netbird/logs.js"
    "htdocs/luci-static/resources/view/netbird/netbird.css"
    "htdocs/luci-static/resources/view/netbird/overview.js"
    "htdocs/luci-static/resources/view/netbird/settings.js"
    "htdocs/luci-static/resources/view/netbird/setup.js"
    "htdocs/luci-static/resources/view/netbird/status.js"
    "htdocs/luci-static/resources/view/netbird/versions.js"
    "po/templates/netbird.pot"
    "po/zh_Hans/netbird.po"
    "root/etc/config/netbird"
    "root/etc/config/netbird_bin"
    "root/etc/init.d/luci-netbird-watchdog"
    "root/etc/init.d/netbird-settings"
    "root/etc/uci-defaults/99-luci-app-netbird"
    "root/usr/share/luci-app-netbird/defaults/netbird.uci"
    "root/usr/share/luci/menu.d/luci-app-netbird.json"
    "root/usr/share/netbird/netbird-autoreconnect.sh"
    "root/usr/share/rpcd/acl.d/luci-app-netbird.json"
    "root/usr/share/rpcd/ucode/lib/envelope.uc"
    "root/usr/share/rpcd/ucode/lib/netbird_cli.uc"
    "root/usr/share/rpcd/ucode/lib/paths.uc"
    "root/usr/share/rpcd/ucode/lib/sanitize.uc"
    "root/usr/share/rpcd/ucode/lib/shell.uc"
    "root/usr/share/rpcd/ucode/lib/state.uc"
    "root/usr/share/rpcd/ucode/netbird.uc"
  ];

  # Vendored LuCI theme (jerrykuku/luci-theme-argon, the ucode-era master
  # layout; not in any official feed).  Every file in the repo root is part
  # of the package (htdocs, ucode templates, uci-defaults, rpcd helper), so
  # the file list is generated by walking the fetched source at eval time.
  # Theme activation happens through the package's own
  # root/etc/uci-defaults/30_luci-theme-argon; the wget-any dependency
  # resolves because uclient-fetch (base system) PROVIDES @wget-any.  Exec
  # bits lost to the patches mechanism's 644 installs are restored by
  # files/etc/uci-defaults/98-luci-apps-setup at first boot.
  argonApp = pkgs.fetchFromGitHub {
    owner = "jerrykuku";
    repo = "luci-theme-argon";
    rev = "ddefe5f05ca334dba10d2d65d25ebf14e986ee88";
    hash = "sha256-DzyrTzHEfBFaRCqBZaIg1wmqKIbiFHyh7Hey9HiuP78=";
  };
  # Shared recursive-walk helper, reused for every vendored package below
  # where "the whole repo is the package source" (no hand-curated file
  # list needed, unlike luci-app-netbird's). Symlinked directories (e.g.
  # po/zh_Hans -> po/zh_CN, a common locale-alias pattern) report type
  # "symlink" from readDir without resolving -- treating those as plain
  # files broke the build outright ("install: omitting directory") since
  # `install -Dm644` refuses to copy a directory. Detect that case by
  # attempting readDir on the target and recursing if it succeeds.
  walkDir = prefix: dir:
    builtins.concatMap
      (name:
        let
          rel = if prefix == "" then name else "${prefix}/${name}";
          type = (builtins.readDir dir)."${name}";
          isDir = type == "directory" || (type == "symlink" &&
            (builtins.tryEval (builtins.readDir (dir + "/${name}"))).success);
        in
        if isDir
        then walkDir rel (dir + "/${name}")
        else [ rel ])
      (builtins.attrNames (builtins.readDir dir));
  argonFiles = walkDir "" argonApp;

  # Portable-router LuCI extras (all vendored, none in any official feed):
  # bandwidth-adjacent status widgets + a speed test + a LuCI-UI MAC
  # randomizer (we already built our own boot-time MAC randomization --
  # files/etc/init.d/randomize-wwan-mac -- this is separate/redundant
  # prior art the user asked for anyway, see the LuCI-addons discussion).
  internetDetectorSrc = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-internet-detector";
    rev = "a4ac581a57121de0c6e8628028eaaea36a524576";
    hash = "sha256-LmBjlyxwfFjHL33JnvZxRmtpEZD/7+haiSNKa6mSGBY=";
  };
  # Monorepo: only vendor the core daemon + the LuCI UI, skip the optional
  # notification modules (mod-email/mod-telegram/mod-modem-restart) -- not
  # needed right now, can be added the same way later if wanted.
  internetDetectorCoreFiles = walkDir "" (internetDetectorSrc + "/internet-detector");
  internetDetectorLuciFiles = walkDir "" (internetDetectorSrc + "/luci-app-internet-detector");

  tempStatusApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-temp-status";
    rev = "7c47517c1cd3d1ccf52eda9237279a45d5884e34";
    hash = "sha256-ZL5OuT67Qy7t/y5fnuQKH8wpWFrodOgw+ZiMLKJK97Q=";
  };
  tempStatusFiles = walkDir "" tempStatusApp;

  cpuStatusApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-cpu-status";
    rev = "d25a968ba844fc9050d4de312f81eb2a495113a2";
    hash = "sha256-eP93dJwq11huPt5wZiTxkRBv6EqAClb15fBCt7A5vTM=";
  };
  cpuStatusFiles = walkDir "" cpuStatusApp;

  # PKG_UNPACK in this package's Makefile directly execs .prepare.sh by
  # path, but the patches mechanism below installs every file at mode 644,
  # so the buildroot's unpack step dies with "Error 126" mid-compile --
  # where the usual boot-time chmod-fixup pattern cannot reach it. Missed
  # on the first vendoring pass and it broke a multi-hour rebuild. Fixed
  # with a locally patched Makefile that invokes it via `sh`; see
  # ./patches/luci-app-netspeedtest-Makefile for the full write-up.
  netspeedtestApp = pkgs.fetchFromGitHub {
    owner = "muink";
    repo = "luci-app-netspeedtest";
    rev = "11147316267a2046ca6457f1b695e2efdf476891";
    hash = "sha256-6B9764jSNdO2wPuzyw/P1lUeFPFRG3IEiIvgzUWmYrM=";
  };
  netspeedtestFiles =
    builtins.filter (f: f != "Makefile") (walkDir "" netspeedtestApp);

  # Repo dir is "luci-app-log" but the package's own PKG_NAME is
  # luci-app-log-viewer -- vendor path below uses the real package name.
  logViewerApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-log";
    rev = "4d5601b7f6c639550d5a257b402b4ce73a06cfbf";
    hash = "sha256-T5UZ2ogAWT/kLbj50z/lsYiUIr9WouRhju/ftKVwhOA=";
  };
  logViewerFiles = walkDir "" logViewerApp;

  interfacesStatsApp = pkgs.fetchFromGitHub {
    owner = "gSpotx2f";
    repo = "luci-app-interfaces-statistics";
    rev = "a53851f3beade7360e397e6f580855c4a39dd300";
    hash = "sha256-mAzv5p3Hd3v6E/5rlV2rrwV80K4KbyLCqfC/yAcaMQg=";
  };
  interfacesStatsFiles = walkDir "" interfacesStatsApp;

  ipinfoApp = pkgs.fetchFromGitHub {
    owner = "animegasan";
    repo = "luci-app-ipinfo";
    rev = "fb9948abe3bfe658c8c47d759b3b8ae87bb1d5d1";
    hash = "sha256-k9jjNVjTRa3V9xSZ2zIaq+2Xn/Tp9Tv56mjAp1660To=";
  };
  ipinfoFiles = walkDir "" ipinfoApp;

  openwrt = inputs.nix-openwrt.lib.build {
    inherit pkgs;
    src = pkgs.fetchFromGitHub {
      owner = "ritiek";
      repo = "openwrt";
      rev = "ad633d4568c054fcf0e6ed89b48e4d36a7651c7f";
      hash = "sha256-P1cWrcC09OPyvcVd8+ygZU0jmRTKHTgqRaclXoSI3bI=";
    };
    config = ./config.seed;
    target = "sunxi";
    subtarget = "cortexa55";
    profile = "radxa_cubie-a5e";
    # Pinned by the bootstrap build (set to pkgs.lib.fakeHash, build once,
    # and replace with the `got:` hash nix reports).
    downloadsHash = "sha256-ikSScTd9tmOLQ2IlNDONYzt8XNYmwmhFOwUTNWpTM7o=";

    # See the "Go on an aarch64 build host" note above.
    extraBuildInputs = [ pkgs.go ];
    extraConfig = ''
      CONFIG_GOLANG_BUILD_BOOTSTRAP=n
      CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT=${pkgs.go}/share/go

      # Build the ImageBuilder, which is what makes incremental rebuilds
      # possible at all.  nix-openwrt has two derivations: the full build
      # (toolchain + kernel + every package -- hours) and mkImage (unpacks
      # the ImageBuilder tarball and assembles a rootfs -- minutes).  Every
      # entry in `patches` below is spliced into the full build's postPatch
      # as a content-addressed store path, so anything routed through
      # `patches` rebuilds the world on edit; anything routed through
      # `files` (see below) only re-runs mkImage.
      #
      # target/imagebuilder/Config.in declares `config IB ... default
      # BUILDBOT`, and BUILDBOT is off here, so the tarball was never
      # emitted -- which is why mkImage's `tar xf openwrt-imagebuilder-*`
      # used to fail and had to be patched out.  Turning IB on is the fix.
      # Its dependency (!EXTERNAL_TOOLCHAIN) already holds: nix-openwrt
      # builds its own toolchain.  IB_STANDALONE then defaults to y, which
      # embeds the package repositories into the tarball -- required,
      # because mkImage runs in a nix sandbox with no network.
      CONFIG_IB=y
    '';

    patches = {
      "tools/fakeroot/patches/900-einval.patch" =
        ./patches/900-einval-neutralized.patch;
      "package/base-files/Makefile" = ./patches/base-files-Makefile;
      # NOTE: files/ deliberately does NOT appear in this attribute.
      # Everything here is spliced into the *full build's* postPatch as a
      # content-addressed store path (see CONFIG_IB above), so listing a
      # uci-defaults script here made a one-line edit rebuild the entire
      # toolchain, kernel and package set.  The rootfs files are handed to
      # the ImageBuilder instead, via `files = ./files;` below, which only
      # re-runs the cheap mkImage stage.
      #
      # Only genuine source-tree modifications belong here: things the
      # buildroot has to compile or honour at build time (the fakeroot
      # patch and base-files Makefile above, and the vendored in-tree
      # packages below).
      #
      # Two consequences of the move, both improvements:
      #   - nix-openwrt's copyExtraFiles used `install -Dm644`, which
      #     flattened every file to 0644.  The ImageBuilder's file_copy
      #     preserves source modes instead, so the few scripts that are
      #     0755 in git stay executable.
      #   - init.d scripts are unaffected either way: both paths run
      #     prepare_rootfs (include/rootfs.mk), which enables them via
      #     rc.common rather than relying on the mode bit.
    }
    # Vendor the netbird LuCI app into the build tree as an in-tree
    # package; the buildroot then packages it with correct file modes
    # (unlike tree files/, which land mode 644).
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-netbird/${f}";
        value = "${netbirdApp}/luci-app-netbird/${f}";
      })
      netbirdAppFiles)
    # Portable-router LuCI extras: internet-detector's monorepo splits into
    # two packages we actually want (core daemon + LuCI UI); everything
    # else below is "whole repo is the package source", same as argon.
    // builtins.listToAttrs (map
      (f: {
        name = "package/internet-detector/${f}";
        value = "${internetDetectorSrc}/internet-detector/${f}";
      })
      internetDetectorCoreFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-internet-detector/${f}";
        value = "${internetDetectorSrc}/luci-app-internet-detector/${f}";
      })
      internetDetectorLuciFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-temp-status/${f}";
        value = "${tempStatusApp}/${f}";
      })
      tempStatusFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-cpu-status/${f}";
        value = "${cpuStatusApp}/${f}";
      })
      cpuStatusFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-netspeedtest/${f}";
        value = "${netspeedtestApp}/${f}";
      })
      netspeedtestFiles)
    # Locally patched Makefile (sh-invoked .prepare.sh) for the package
    # above.
    // {
      "package/luci-app-netspeedtest/Makefile" =
        ./patches/luci-app-netspeedtest-Makefile;
    }
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-log-viewer/${f}";
        value = "${logViewerApp}/${f}";
      })
      logViewerFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-interfaces-statistics/${f}";
        value = "${interfacesStatsApp}/${f}";
      })
      interfacesStatsFiles)
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-app-ipinfo/${f}";
        value = "${ipinfoApp}/${f}";
      })
      ipinfoFiles)
    # Same for the argon theme (whole repo is the package source).
    // builtins.listToAttrs (map
      (f: {
        name = "package/luci-theme-argon/${f}";
        value = "${argonApp}/${f}";
      })
      argonFiles);
  };
in
let
  imageDrv = openwrt.mkImage {
    # Package set for the ImageBuilder assembly (`make image PACKAGES=...`).
    # `config.seed` above compiles these during the full build, but the
    # ImageBuilder does not inherit the tree config's package selections, so
    # everything beyond the profile defaults must be listed here as well.
    packages = [
      "kmod-aic8800-sdio"
      "aic8800-sdio-firmware"
      "-wpad-basic-mbedtls"
      "wpad-mbedtls"
      "iw-full"
      "tcpdump"
      "ethtool"
      "kmod-sdhci"
      "luci"
      "luci-ssl"
      "adguardhome"
      "luci-app-adguardhome"
      "tailscale"
      "kmod-tun"
      "luci-app-tailscale-community"
      "netbird"
      "luci-app-netbird"
      "conntrack"
      "luci-theme-argon"
      "kmod-wireguard"
      "kmod-rtl8xxxu"
      "mwan3"
      "luci-app-mwan3"
      "nlbwmon"
      "luci-app-nlbwmon"
      "luci-app-sqm"
      "luci-app-samba4"
      "samba4-server"
      "internet-detector"
      "luci-app-internet-detector"
      "luci-app-temp-status"
      "luci-app-cpu-status"
      "luci-app-netspeedtest"
      "luci-app-log-viewer"
      "luci-app-interfaces-statistics"
      "luci-app-ipinfo"
      "travelmate"
      "luci-lib-uqr"
      "luci-app-travelmate"
      "vnstat2"
      "vnstati2"
      "luci-app-vnstat2"
      "ttyd"
      "luci-app-ttyd"
      "natmap"
      "luci-app-natmap"
      "chrony"
      "luci-app-chrony"
      "miniupnpd"
      "rpcd-mod-ucode"
      "luci-app-upnp"
      "kmod-usb-net"
      "kmod-usb-net-rndis"
      "kmod-usb-net-cdc-ether"
      "kmod-usb-net-ipheth"
    ];
    files = ./files;
  };
in
# Two cosmetic tweaks to ayles' mkImage; the build itself is now unmodified.
#
# This used to be a much larger override that replaced mkImage's entire
# buildPhase, because `tar xf .../openwrt-imagebuilder-*.tar.*` failed --
# the ImageBuilder tarball was never built.  CONFIG_IB=y (see extraConfig
# above) fixes that at the source, so the real ImageBuilder stage runs and
# the workaround is gone.  That is what makes files/ edits cheap: they no
# longer touch the full build at all.
#
# Both rewrites go through builtins.replaceStrings on the original strings
# rather than hand-written replacements, so the string context (and with it
# the dependency on the full-build derivation) is preserved.
pkgs.lib.overrideDerivation imageDrv (old: {
  # Name the artifact after the machine, not the distro
  # (openwrt-image-radxa_cubie-a5e-<rev> -> switchwrt-image-...).
  name = builtins.replaceStrings
    [ "openwrt-image-" ]
    [ "switchwrt-image-" ]
    old.name;

  # Also keep the .manifest (the exact package list and versions that went
  # into the rootfs); ayles' artifact collection does not pick it up, and it
  # is the only way to verify the `packages` list above after a build.
  buildPhase = builtins.replaceStrings
    [ "-o -name 'sha256sums' \\)" ]
    [ "-o -name 'sha256sums' -o -name '*.manifest' \\)" ]
    old.buildPhase;
})
