# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/open-archiver.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."open-archiver" = {
    image = "logiclabshq/open-archiver:latest";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver:/var/data/open-archiver:rw"
    ];
    ports = [
      "3035:3000/tcp"
    ];
    dependsOn = [
      "meilisearch"
      "postgres"
      "valkey"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=open-archiver"
      "--network=open-archiver_open-archiver-net"
    ];
    labels = {
      "homepage.description" = "Email archiving";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3035";
      "homepage.icon" = "open-archiver";
      "homepage.name" = "Open Archiver";
    };
  };
  systemd.services."docker-open-archiver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver"
    ];
  };
  virtualisation.oci-containers.containers."meilisearch" = {
    image = "getmeili/meilisearch:v1.15";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver/meilisearch:/meili_data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=meilisearch"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-meilisearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver/meilisearch"
    ];
  };
  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:17-alpine";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver/pgdata:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=postgres"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver/pgdata"
    ];
  };
  virtualisation.oci-containers.containers."tika" = {
    image = "apache/tika:3.2.2.0-full";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=tika"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-tika" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
  };
  virtualisation.oci-containers.containers."valkey" = {
    image = "valkey/valkey:8-alpine";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver/valkeydata:/data:rw"
    ];
    cmd = [ "valkey-server" "--requirepass" "boozy-sushi-lushly-lycirally-atrocious-clinic" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=valkey"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-valkey" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver/valkeydata"
    ];
  };

  # Networks
  systemd.services."docker-network-open-archiver_open-archiver-net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f open-archiver_open-archiver-net";
    };
    script = ''
      docker network inspect open-archiver_open-archiver-net || docker network create open-archiver_open-archiver-net --driver=bridge
    '';
    partOf = [ "docker-compose-open-archiver-root.target" ];
    wantedBy = [ "docker-compose-open-archiver-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-open-archiver-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
