# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/open-archiver.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
    restartUnits = [
      "docker-open-archiver.service"
      "docker-meilisearch.service"
      "docker-postgres.service"
      "docker-tika.service"
      "docker-valkey.service"
    ];
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."open-archiver" = {
    # Pinned rather than :latest so a docker pull can't silently move us
    # across a schema migration. Bump deliberately.
    image = "logiclabshq/open-archiver:v0.6.0";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    # Non-secret tuning. Kept here rather than in the sops-encrypted
    # stack.env so it stays readable and diffable; docker -e overrides
    # --env-file, so these win regardless.
    environment = {
      # v0.6.0 made indexing and ingestion concurrent, defaulting to 4 and
      # 3. v0.5.0 processed one item at a time, so accepting the defaults
      # would be a real step up in peak memory on an 8GB host that is
      # already ~1.6x oversubscribed. Start conservative.
      INDEXING_WORKER_CONCURRENCY = "2";
      INGESTION_EMAIL_CONCURRENCY = "1";
      # Node sizes max-old-space at ~25% of host RAM when unset: every one
      # of the 18 node processes in this container reported a 2096MB heap
      # limit. Nothing enforced a ceiling, so a single runaway parse could
      # take the box. Cap the worker that actually handles large documents.
      INDEXING_WORKER_MAX_OLD_SPACE_MB = "512";
      # The reconcile job is what refills the indexing queue, and it only
      # enqueues INDEX_RECONCILE_PAGE_CAP (default 20) rows per pass. During
      # the post-upgrade full rebuild that throttled throughput to ~473/hr
      # (measured over 13 min: steady bursts of ~25, with the queue sitting
      # at 12 waiting against 26k unindexed rows), which would have taken
      # ~56h. Meilisearch was not the limit; it was idle between bursts.
      # Raise the page cap and the backpressure ceiling so the queue stays
      # fed. Depth is cheap - jobs are small ids in valkey - and actual
      # memory is still bounded by INDEXING_WORKER_CONCURRENCY above.
      INDEX_RECONCILE_PAGE_CAP = "200";
      INDEX_RECONCILE_BACKPRESSURE = "500";
      # Deliberately NOT lowering INDEX_RECONCILE_CRON from its */30 default.
      # Tried "*/2 * * * *" and measured it: throughput fell 736 -> 527/hr
      # and load average went 10.8 -> 26.2 while the queue depth never moved
      # off 7-10. The extra passes only competed for CPU. The enqueue side
      # is not the bottleneck - worker/Meilisearch round-trip time is.
      # v0.6.0 stops archiving unsent drafts by default. This archive was
      # built with drafts included, so preserve existing behaviour rather
      # than silently changing what gets captured. Set to "false" to adopt
      # the new upstream default.
      ARCHIVE_DRAFTS = "true";
    };
    volumes = [
      "${homelabMediaPath}/services/open-archiver:/var/data/open-archiver:rw"
    ];
    ports = [
      "3035:3000/tcp"
    ];
    dependsOn = [
      "meilisearch"
      "postgres"
      "valkey"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=open-archiver"
      "--network=open-archiver_open-archiver-net"
    ];
    labels = {
      "homepage.description" = "Email archiving";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:3035";
      "homepage.icon" = "open-archiver";
      "homepage.name" = "Open Archiver";
    };
  };
  systemd.services."docker-open-archiver" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver"
    ];
  };
  virtualisation.oci-containers.containers."meilisearch" = {
    # Matches the version upstream ships with open-archiver v0.6.0.
    # Meilisearch refuses to open a DB written by a different version, so
    # this bump requires the old data.ms to be moved aside first. That is
    # safe here: the index is a secondary store rebuilt from Postgres.
    image = "getmeili/meilisearch:v1.38";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver/meilisearch:/meili_data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=meilisearch"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-meilisearch" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver/meilisearch"
    ];
  };
  virtualisation.oci-containers.containers."postgres" = {
    image = "postgres:17-alpine";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver/pgdata:/var/lib/postgresql/data:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=postgres"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-postgres" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver/pgdata"
    ];
  };
  virtualisation.oci-containers.containers."tika" = {
    image = "apache/tika:3.2.2.0-full";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=tika"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-tika" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
  };
  virtualisation.oci-containers.containers."valkey" = {
    image = "valkey/valkey:8-alpine";
    environmentFiles = [
      config.sops.secrets."compose/open-archiver.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/open-archiver/valkeydata:/data:rw"
    ];
    cmd = [ "valkey-server" "--requirepass" "boozy-sushi-lushly-lycirally-atrocious-clinic" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=valkey"
      "--network=open-archiver_open-archiver-net"
    ];
  };
  systemd.services."docker-valkey" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    requires = [
      "docker-network-open-archiver_open-archiver-net.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/open-archiver/valkeydata"
    ];
  };

  # Networks
  systemd.services."docker-network-open-archiver_open-archiver-net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f open-archiver_open-archiver-net";
    };
    script = ''
      docker network inspect open-archiver_open-archiver-net || docker network create open-archiver_open-archiver-net --driver=bridge
    '';
    partOf = [ "docker-compose-open-archiver-root.target" ];
    wantedBy = [ "docker-compose-open-archiver-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-open-archiver-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
