# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, ... }:

let
  # Configuration
  webUIPort = 9283;
  internalWebUIPort = 19283;

  # Import lazy-loading module
  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };
  
  # Generate lazy-loading services
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Grocy";
    dockerServiceName = "grocy";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [ "/media/HOMELAB_MEDIA/services/grocy" ];
  };

in {
  sops.secrets."compose/grocy.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."grocy" = {
    image = "lscr.io/linuxserver/grocy:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      config.sops.secrets."compose/grocy.env".path
    ];
    volumes = [
      "/media/HOMELAB_MEDIA/services/grocy:/config:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:80/tcp"  # Internal port only
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=grocy"
      "--network=grocy_default"
    ];
  };
  systemd.services."docker-grocy" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-grocy_default.service"
    ];
    requires = [
      "docker-network-grocy_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/grocy"
    ];
    # Bind to root target
    partOf = [ "docker-compose-grocy-root.target" ];
    wantedBy = [ "docker-compose-grocy-root.target" ];
  };

  # Networks
  systemd.services."docker-network-grocy_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f grocy_default";
    };
    script = ''
      docker network inspect grocy_default || docker network create grocy_default
    '';
    partOf = [ "docker-compose-grocy-root.target" ];
    wantedBy = [ "docker-compose-grocy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-grocy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} 
// lazyLoadingServices
