# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, ... }:

let
  # Configuration
  webUIPort = 9283;
  internalWebUIPort = 19283;

  # Helper script to handle connections
  grocyConnectionHandler = pkgs.writeShellScript "grocy-connection-handler" ''
    echo "Connection received at $(date)" >&2

    # Check if Grocy container is running
    if ! ${pkgs.systemd}/bin/systemctl is-active --quiet docker-grocy.service; then
      echo "Starting Grocy..." >&2
      ${pkgs.systemd}/bin/systemctl start docker-grocy.service

      # Wait for Grocy to be ready
      echo "Waiting for Grocy to start..." >&2
      for i in $(seq 1 30); do
        if ${pkgs.curl}/bin/curl -s -f --connect-timeout 2 http://127.0.0.1:${toString internalWebUIPort}/ >/dev/null 2>&1; then
          echo "Grocy is ready!" >&2
          break
        fi
        if [ $i -eq 30 ]; then
          echo "Grocy failed to start, sending error page" >&2
          cat << 'EOF'
HTTP/1.1 503 Service Unavailable
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html><head><title>Service Starting</title></head>
<body><h1>Grocy is starting...</h1><p>Please wait a moment and refresh the page.</p></body></html>
EOF
          exit 1
        fi
        sleep 2
      done
    fi

    echo "Grocy is ready, proxying connection..." >&2
    # Now proxy the connection to the running Grocy
    exec ${pkgs.socat}/bin/socat - TCP:127.0.0.1:${toString internalWebUIPort}
  '';

in {
  sops.secrets."compose/grocy.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."grocy" = {
    image = "lscr.io/linuxserver/grocy:latest";
    environment = {
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      config.sops.secrets."compose/grocy.env".path
    ];
    volumes = [
      "/media/HOMELAB_MEDIA/services/grocy:/config:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:80/tcp"  # Internal port only
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=grocy"
      "--network=grocy_default"
    ];
  };
  systemd.services."docker-grocy" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-grocy_default.service"
    ];
    requires = [
      "docker-network-grocy_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/grocy"
    ];
    # Bind to root target
    partOf = [ "docker-compose-grocy-root.target" ];
    wantedBy = [ "docker-compose-grocy-root.target" ];
    # Start timer when service starts, stop when service stops
    postStart = ''
      ${pkgs.systemd}/bin/systemctl start grocy-idle-stop.timer
    '';
    preStop = ''
      ${pkgs.systemd}/bin/systemctl stop grocy-idle-stop.timer || true
    '';
  };

  # Networks
  systemd.services."docker-network-grocy_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f grocy_default";
    };
    script = ''
      docker network inspect grocy_default || docker network create grocy_default
    '';
    partOf = [ "docker-compose-grocy-root.target" ];
    wantedBy = [ "docker-compose-grocy-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-grocy-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  # Port listener that starts Grocy on any connection attempt
  systemd.services."grocy-autostart" = {
    description = "Grocy auto-start on connection";
    serviceConfig = {
      Restart = "always";
      RestartSec = "5s";
    };
    script = ''
      echo "Starting Grocy auto-start proxy on port ${toString webUIPort}..."
      exec ${pkgs.socat}/bin/socat TCP4-LISTEN:${toString webUIPort},reuseaddr,fork EXEC:${grocyConnectionHandler}
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/grocy"
    ];
    # Bind to root target so it stops when target stops
    partOf = [ "docker-compose-grocy-root.target" ];
    wantedBy = [ "docker-compose-grocy-root.target" ];
    after = [ "docker.service" ];
  };

  # Timer-based service to stop when idle - started manually by docker-grocy
  systemd.timers."grocy-idle-stop" = {
    timerConfig = {
      OnCalendar = "*:0/5";  # Every 5 minutes, more explicit format
      Persistent = true;
      Unit = "grocy-idle-stop.service";
    };
  };

  systemd.services."grocy-idle-stop" = {
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      # Check for active connections (both proxy port and internal port)
      proxy_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString webUIPort}" | grep ESTABLISHED | wc -l)
      internal_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString internalWebUIPort}" | grep ESTABLISHED | wc -l)
      total_connections=$((proxy_connections + internal_connections))

      if [ "$total_connections" -eq 0 ]; then
        echo "$(date): No active connections for 5+ minutes, stopping Grocy"
        ${pkgs.systemd}/bin/systemctl stop docker-grocy.service
        # Timer will automatically stop due to partOf dependency
      else
        echo "$(date): $total_connections active connections, keeping Grocy running"
      fi
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/grocy"
    ];
    # Also bind to root target for additional safety
    partOf = [ "docker-compose-grocy-root.target" ];
  };
}
