[".oh-my-zsh/custom/plugins/zsh-autosuggestions"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-autosuggestions.git"
  refreshPeriod = "168h"
  clone.args = ["--depth", "1"]

[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
  type = "git-repo"
  url = "https://github.com/zsh-users/zsh-syntax-highlighting.git"
  refreshPeriod = "168h"
  clone.args = ["--depth", "1"]

[".oh-my-zsh/custom/themes/powerlevel10k"]
  type = "git-repo"
  url = "https://github.com/romkatv/powerlevel10k.git"
  refreshPeriod = "168h"
  clone.args = ["--depth", "1"]

[".config/nvim"]
  # type = "git-repo"
  # url = "https://github.com/NvChad/NvChad.git"
  # refreshPeriod = "168h"
  # clone.args = ["--depth", "1"]

  # Ideally, we should be treating this a git-repo and not an archive.
  # However, due to a bug in chezmoi, this seems like the best workaround
  # for now:
  # https://github.com/twpayne/chezmoi/issues/1614#issuecomment-1058933765
  type = "archive"
  url = "https://github.com/NvChad/NvChad/archive/master.tar.gz"
  stripComponents = 1
  exact = false

[".local/bin/transfuse"]
  type = "file"
  url = "https://gitlab.com/cscs/transfuse/raw/master/transfuse.sh"
  executable = true
  refreshPeriod = "168h"


# Fonts

[".local/share/fonts/InconsolataGoNerdFontMono-Regular.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/InconsolataGo/Regular/InconsolataGoNerdFontMono-Regular.ttf"
  executable = false
  refreshPeriod = "168h"
[".local/share/fonts/InconsolataGoNerdFontMono-Bold.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/InconsolataGo/Bold/InconsolataGoNerdFontMono-Bold.ttf"
  executable = false
  refreshPeriod = "168h"

[".local/share/fonts/FantasqueSansMNerdFontMono-Regular.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FantasqueSansMono/Regular/FantasqueSansMNerdFontMono-Regular.ttf"
  executable = false
  refreshPeriod = "168h"
[".local/share/fonts/FantasqueSansMNerdFontMono-Italic.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FantasqueSansMono/Italic/FantasqueSansMNerdFontMono-Italic.ttf"
  executable = false
  refreshPeriod = "168h"
[".local/share/fonts/FantasqueSansMNerdFontMono-Bold.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FantasqueSansMono/Bold/FantasqueSansMNerdFontMono-Bold.ttf"
  executable = false
  refreshPeriod = "168h"
[".local/share/fonts/FantasqueSansMNerdFontMono-BoldItalic.ttf"]
  type = "file"
  url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FantasqueSansMono/Bold-Italic/FantasqueSansMNerdFontMono-BoldItalic.ttf"
  executable = false
  refreshPeriod = "168h"

[".local/share/fonts/DroidSansMNerdFontMono-Regular.otf"]
  type = "file"
  url = "https://raw.githubusercontent.com/ryanoasis/nerd-fonts/master/patched-fonts/DroidSansMono/DroidSansMNerdFontMono-Regular.otf"
  executable = false
  refreshPeriod = "168h"
