# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 6333;
  internalWebUIPort = 16333;

  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Qdrant";
    dockerServiceName = "qdrant";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/qdrant/config"
      "${homelabMediaPath}/services/qdrant/storage"
    ];
    silent = true;
    idleCheckInterval = "*-*-* 0/2:00:00";
    healthEndpoint = "/dashboard";
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets."compose/qdrant.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."qdrant" = {
    image = "haktansuren/qdrant-pi5-fixed-jemalloc:latest";
    environmentFiles = [
      config.sops.secrets."compose/qdrant.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/qdrant/config:/qdrant/config:rw"
      "${homelabMediaPath}/services/qdrant/storage:/qdrant/storage:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:6333/tcp"
      "6334:6334/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=qdrant"
      "--network=qdrant_default"
    ];
  };
  systemd.services."docker-qdrant" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-qdrant_default.service"
    ];
    requires = [
      "docker-network-qdrant_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/qdrant/config"
      "${homelabMediaPath}/services/qdrant/storage"
    ];
    partOf = [ "docker-compose-qdrant-root.target" ];
    wantedBy = [ "docker-compose-qdrant-root.target" ];
  };

  # Networks
  systemd.services."docker-network-qdrant_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f qdrant_default";
    };
    script = ''
      docker network inspect qdrant_default || docker network create qdrant_default
    '';
    partOf = [ "docker-compose-qdrant-root.target" ];
    wantedBy = [ "docker-compose-qdrant-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-qdrant-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
