# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/qdrant.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."qdrant" = {
    # XXX: The official image: qdrant/qdrant:latest suffers from this issue:
    #      https://github.com/qdrant/qdrant/issues/3831
    image = "haktansuren/qdrant-pi5-fixed-jemalloc:latest";
    environmentFiles = [
      config.sops.secrets."compose/qdrant.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/qdrant/config:/qdrant/config:rw"
      "${homelabMediaPath}/services/qdrant/storage:/qdrant/storage:rw"
    ];
    ports = [
      "6333:6333/tcp"
      "6334:6334/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=qdrant"
      "--network=qdrant_default"
    ];
    labels = {
      "homepage.description" = "Vector search engine";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:6333/dashboard";
      "homepage.icon" = "qdrant";
      "homepage.name" = "Qdrant";
    };
  };
  systemd.services."docker-qdrant" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-qdrant_default.service"
    ];
    requires = [
      "docker-network-qdrant_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/qdrant/config"
      "${homelabMediaPath}/services/qdrant/storage"
    ];
  };

  # Networks
  systemd.services."docker-network-qdrant_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f qdrant_default";
    };
    script = ''
      docker network inspect qdrant_default || docker network create qdrant_default
    '';
    partOf = [ "docker-compose-qdrant-root.target" ];
    wantedBy = [ "docker-compose-qdrant-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-qdrant-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
