# Auto-generated using compose2nix v0.3.1.
{ config, pkgs, lib, homelabMediaPath, ... }:

let
  # Configuration
  webUIPort = 3020;
  internalWebUIPort = 13020;

  # Import lazy-loading module
  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };
  
  # Generate lazy-loading services with custom commands for multi-service stack
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Ollama & Open-WebUI";
    dockerServiceName = "open-webui";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [ "${homelabMediaPath}/services/ollama-webui/ollama" "${homelabMediaPath}/services/ollama-webui/open-webui" ];
    rootTarget = "docker-compose-ollama-webui-root.target";
    startCommand = "systemctl start docker-ollama.service docker-open-webui.service";
    stopCommand = "systemctl stop docker-compose-ollama-webui-root.target";
    waitTimeout = 180; # 3 minutes for ollama and webui stack
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets."compose/ollama-webui.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ollama" = {
    image = "ollama/ollama:latest";
    volumes = [
      "${homelabMediaPath}/services/ollama-webui/ollama:/root/.ollama:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=ollama"
      "--network=ollama-webui_default"
    ];
  };
  systemd.services."docker-ollama" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ollama-webui_default.service"
    ];
    requires = [
      "docker-network-ollama-webui_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/ollama-webui/ollama"
    ];
    # Bind to root target
    partOf = [ "docker-compose-ollama-webui-root.target" ];
    wantedBy = [ "docker-compose-ollama-webui-root.target" ];
  };
  virtualisation.oci-containers.containers."open-webui" = {
    image = "ghcr.io/open-webui/open-webui:main";
    # environment = {
    #   "OLLAMA_BASE_URL" = "http://ollama:11434";
    # };
    environmentFiles = [
      config.sops.secrets."compose/ollama-webui.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/ollama-webui/open-webui:/app/backend/data:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8080/tcp"  # Internal port only
    ];
    # Removed dependsOn to make services independent
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--add-host=host.docker.internal:host-gateway"
      "--network-alias=open-webui"
      "--network=ollama-webui_default"
    ];
  };
  systemd.services."docker-open-webui" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ollama-webui_default.service"
    ];
    requires = [
      "docker-network-ollama-webui_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/ollama-webui/open-webui"
    ];
    # Bind to root target
    partOf = [ "docker-compose-ollama-webui-root.target" ];
    wantedBy = [ "docker-compose-ollama-webui-root.target" ];
  };

  # Networks
  systemd.services."docker-network-ollama-webui_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ollama-webui_default";
    };
    script = ''
      docker network inspect ollama-webui_default || docker network create ollama-webui_default
    '';
    partOf = [ "docker-compose-ollama-webui-root.target" ];
    wantedBy = [ "docker-compose-ollama-webui-root.target" ];
  };

  # Builds
  # systemd.services."docker-build-open-webui" = {
  #   path = [ pkgs.docker pkgs.git ];
  #   serviceConfig = {
  #     Type = "oneshot";
  #     TimeoutSec = 300;
  #   };
  #   script = ''
  #     cd /etc/nixos
  #     docker build -t ghcr.io/open-webui/open-webui:main --build-arg OLLAMA_BASE_URL=/ollama .
  #   '';
  # };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ollama-webui-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
