# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 9090;
  internalWebUIPort = 19090;

  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Linkding";
    dockerServiceName = "linkding";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/linkding/data"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets."compose/linkding.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."linkding" = {
    image = "sissbruecker/linkding:latest";
    environmentFiles = [
      config.sops.secrets."compose/linkding.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/linkding/data:/etc/linkding/data:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:9090/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=linkding"
      "--network=linkding_default"
    ];
  };
  systemd.services."docker-linkding" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-linkding_default.service"
    ];
    requires = [
      "docker-network-linkding_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/linkding/data"
    ];
    partOf = [ "docker-compose-linkding-root.target" ];
    wantedBy = [ "docker-compose-linkding-root.target" ];
  };

  # Networks
  systemd.services."docker-network-linkding_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f linkding_default";
    };
    script = ''
      docker network inspect linkding_default || docker network create linkding_default
    '';
    partOf = [ "docker-compose-linkding-root.target" ];
    wantedBy = [ "docker-compose-linkding-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-linkding-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
