# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/linkding.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."linkding" = {
    image = "sissbruecker/linkding:latest";
    environmentFiles = [
      config.sops.secrets."compose/linkding.env".path
    ];
    volumes = [
      "/media/HOMELAB_MEDIA/services/linkding/data:/etc/linkding/data:rw"
    ];
    ports = [
      "9090:9090/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=linkding"
      "--network=linkding_default"
    ];
    labels = {
      "homepage.description" = "Bookmark manager";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:9090";
      "homepage.icon" = "linkding";
      "homepage.name" = "Linkding";
    };
  };
  systemd.services."docker-linkding" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-linkding_default.service"
    ];
    requires = [
      "docker-network-linkding_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/linkding/data"
    ];
  };

  # Networks
  systemd.services."docker-network-linkding_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f linkding_default";
    };
    script = ''
      docker network inspect linkding_default || docker network create linkding_default
    '';
    partOf = [ "docker-compose-linkding-root.target" ];
    wantedBy = [ "docker-compose-linkding-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-linkding-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
