# Auto-generated by compose2nix.

{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/ryot.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
    restartUnits = [
      "docker-ryot.service"
      "docker-ryot-db.service"
    ];
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."ryot" = {
    image = "ghcr.io/ignisda/ryot:v10";
    environmentFiles = [
      config.sops.secrets."compose/ryot.env".path
    ];
    ports = [
      "8001:8000/tcp"
    ];
    dependsOn = [
      "ryot-db"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=ryot"
      "--network=ryot_default"
      "--add-host=host.docker.internal:host-gateway"
    ];
    labels = {
      "homepage.description" = "Media tracking";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:8001";
      "homepage.icon" = "ryot";
      "homepage.name" = "Ryot";
    };
  };
  systemd.services."docker-ryot" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ryot_default.service"
    ];
    requires = [
      "docker-network-ryot_default.service"
    ];
  };
  virtualisation.oci-containers.containers."ryot-db" = {
    image = "postgres:18-alpine";
    environmentFiles = [
      config.sops.secrets."compose/ryot.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/ryot/postgres:/var/lib/postgresql:rw"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=ryot-db"
      "--network=ryot_default"
    ];
  };
  systemd.services."docker-ryot-db" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-ryot_default.service"
    ];
    requires = [
      "docker-network-ryot_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/ryot/postgres"
    ];
  };

  # Networks
  systemd.services."docker-network-ryot_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f ryot_default";
    };
    script = ''
      docker network inspect ryot_default || docker network create ryot_default
    '';
    partOf = [ "docker-compose-ryot-root.target" ];
    wantedBy = [ "docker-compose-ryot-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-ryot-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
