# Auto-generated using compose2nix v0.3.1.
{ pkgs, lib, homelabMediaPath, ... }:

let
  # Configuration
  webUIPort = 3000;
  internalWebUIPort = 13000;

  # Import lazy-loading module
  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };
  
  # Generate lazy-loading services with custom commands for multi-service stack
  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Habitica";
    dockerServiceName = "habitica-server";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [ "${homelabMediaPath}/services/habitica/db" "${homelabMediaPath}/services/habitica/dbconf" ];
    rootTarget = "docker-compose-habitica-root.target";
    startCommand = "systemctl start docker-habitica-mongo.service docker-habitica-server.service";
    stopCommand = "systemctl stop docker-compose-habitica-root.target";
    waitTimeout = 180; # 3 minutes for habitica + mongo stack
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."habitica-mongo" = {
    image = "docker.io/mongo:5.0";
    volumes = [
      "${homelabMediaPath}/services/habitica/db:/data/db:rw"
      "${homelabMediaPath}/services/habitica/dbconf:/data/configdb:rw"
    ];
    cmd = [ "--replSet" "rs" "--bind_ip_all" "--port" "27017" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=echo \"try { rs.status() } catch (err) { rs.initiate() }\" | mongosh --port 27017 --quiet"
      "--health-interval=10s"
      "--health-retries=30"
      "--health-start-interval=1s"
      "--health-start-period=0s"
      "--health-timeout=30s"
      "--hostname=mongo"
      "--network-alias=mongo"
      "--network-alias=mongo"
      "--network=habitica_habitica"
    ];
  };
  systemd.services."docker-habitica-mongo" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-habitica_habitica.service"
    ];
    requires = [
      "docker-network-habitica_habitica.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/habitica/db"
      "${homelabMediaPath}/services/habitica/dbconf"
    ];
    # Bind to root target
    partOf = [ "docker-compose-habitica-root.target" ];
    wantedBy = [ "docker-compose-habitica-root.target" ];
  };
  virtualisation.oci-containers.containers."habitica-server" = {
    image = "docker.io/awinterstein/habitica-server:latest";
    environment = {
      "BASE_URL" = "http://127.0.0.1:8080";
      "INVITE_ONLY" = "false";
      "NODE_DB_URI" = "mongodb://mongo/habitica";
    };
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:3000/tcp"  # Internal port only
    ];
    dependsOn = [
      "habitica-mongo"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=server"
      "--network=habitica_habitica"
    ];
  };
  systemd.services."docker-habitica-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-habitica_habitica.service"
    ];
    requires = [
      "docker-network-habitica_habitica.service"
    ];
    # Bind to root target
    partOf = [ "docker-compose-habitica-root.target" ];
    wantedBy = [ "docker-compose-habitica-root.target" ];
  };

  # Networks
  systemd.services."docker-network-habitica_habitica" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f habitica_habitica";
    };
    script = ''
      docker network inspect habitica_habitica || docker network create habitica_habitica --driver=bridge
    '';
    partOf = [ "docker-compose-habitica-root.target" ];
    wantedBy = [ "docker-compose-habitica-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-habitica-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
