# Auto-generated using compose2nix v0.3.1.
{ config, pkgs, lib, ... }:

{
  sops.secrets."compose/habitica.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."habitica-client" = {
    image = "docker.io/ritiek/habitica-client:latest";
    environmentFiles = [
      config.sops.secrets."compose/habitica.env".path
    ];
    ports = [
      "8025:80/tcp"
    ];
    dependsOn = [
      "habitica-server"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=client"
      "--network=habitica_habitica"
    ];
  };
  systemd.services."docker-habitica-client" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-habitica_habitica.service"
    ];
    requires = [
      "docker-network-habitica_habitica.service"
    ];
  };
  virtualisation.oci-containers.containers."habitica-mongo" = {
    image = "docker.io/mongo:5.0";
    environmentFiles = [
      config.sops.secrets."compose/habitica.env".path
    ];
    ports = [
      "27017:27017/tcp"
    ];
    cmd = [ "--replSet" "rs" "--bind_ip_all" "--port" "27017" ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--health-cmd=echo \"try { rs.status() } catch (err) { rs.initiate() }\" | mongosh --port 27017 --quiet"
      "--health-interval=10s"
      "--health-retries=30"
      "--health-start-interval=1s"
      "--health-start-period=0s"
      "--health-timeout=30s"
      "--network-alias=mongo"
      "--network=habitica_habitica"
    ];
  };
  systemd.services."docker-habitica-mongo" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-habitica_habitica.service"
    ];
    requires = [
      "docker-network-habitica_habitica.service"
    ];
  };
  virtualisation.oci-containers.containers."habitica-server" = {
    image = "docker.io/ritiek/habitica-server:latest";
    environmentFiles = [
      config.sops.secrets."compose/habitica.env".path
    ];
    ports = [
      "8024:3000/tcp"
    ];
    dependsOn = [
      "habitica-mongo"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=server"
      "--network=habitica_habitica"
    ];
  };
  systemd.services."docker-habitica-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "no";
    };
    after = [
      "docker-network-habitica_habitica.service"
    ];
    requires = [
      "docker-network-habitica_habitica.service"
    ];
  };

  # Networks
  systemd.services."docker-network-habitica_habitica" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f habitica_habitica";
    };
    script = ''
      docker network inspect habitica_habitica || docker network create habitica_habitica --driver=bridge
    '';
    partOf = [ "docker-compose-habitica-root.target" ];
    wantedBy = [ "docker-compose-habitica-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-habitica-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
