# Hand-written in the compose2nix style used by sibling services in this
# directory, but without a sops-managed stack.env: OpenDesign needs no
# secret here because OD_DISABLE_API_AUTH=1 is set below (see rationale).

{ pkgs, lib, config, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."open-design" = {
    image = "ghcr.io/nexu-io/od:latest";
    environment = {
      NODE_ENV = "production";
      NODE_OPTIONS = "--max-old-space-size=192";
      OD_BIND_HOST = "0.0.0.0";
      OD_PORT = "7456";
      OD_WEB_PORT = "7456";
      # od mcp's stdio client has no code path to send an Authorization
      # header, so an enforced OD_API_TOKEN would 401 every MCP tool call
      # from other hosts. Tailscale (this host is only reachable via
      # pilab.lion-zebra.ts.net) is the trust boundary instead, matching
      # upstream's own guidance for deployments behind an already-trusted
      # private network.
      OD_DISABLE_API_AUTH = "1";
    };
    volumes = [
      "open-design-data:/app/.od"
    ];
    ports = [
      "7456:7456/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=open-design"
      "--network=open-design_open-design-net"
    ];
    labels = {
      "homepage.description" = "AI design tool (MCP daemon)";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:7456";
      "homepage.icon" = "open-design";
      "homepage.name" = "OpenDesign";
    };
  };
  systemd.services."docker-open-design" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-open-design_open-design-net.service"
    ];
    requires = [
      "docker-network-open-design_open-design-net.service"
    ];
  };

  # Networks
  systemd.services."docker-network-open-design_open-design-net" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "${pkgs.docker}/bin/docker network rm -f open-design_open-design-net";
    };
    script = ''
      docker network inspect open-design_open-design-net || docker network create open-design_open-design-net --driver=bridge
    '';
    partOf = [ "docker-compose-open-design-root.target" ];
    wantedBy = [ "docker-compose-open-design-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-open-design-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
