# Migrated from conduwuit to continuwuity (community fork).
# CONDUWUIT_* env vars remain valid as compat aliases — stack.env unchanged.
{ pkgs, lib, config, homelabMediaPath, ... }:

{
  sops.secrets."compose/continuwuity.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."continuwuity" = {
    image = "forgejo.ellis.link/continuwuation/continuwuity:latest";
    cmd = [ "/sbin/conduwuit" ];
    environmentFiles = [
      config.sops.secrets."compose/continuwuity.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/continuwuity/data:/var/lib/matrix-conduit:rw"
    ];
    ports = [
      "6168:6168/tcp"
    ];
    user = "1001:1001";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=conduit"
      "--network=continuwuity_default"
    ];
    labels = {
      "homepage.description" = "Continuwuity Homeserver";
      "homepage.group" = "Services";
      "homepage.href" = "http://pilab.lion-zebra.ts.net:6168";
      "homepage.icon" = "matrix";
      "homepage.name" = "Matrix";
    };
  };
  systemd.services."docker-continuwuity" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-continuwuity_default.service"
    ];
    requires = [
      "docker-network-continuwuity_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/continuwuity/data"
    ];
  };

  # Networks
  systemd.services."docker-network-continuwuity_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f continuwuity_default";
    };
    script = ''
      docker network inspect continuwuity_default || docker network create continuwuity_default
    '';
    partOf = [ "docker-compose-continuwuity-root.target" ];
    wantedBy = [ "docker-compose-continuwuity-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-continuwuity-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
