# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, ... }:

let
  # Configuration
  webUIPort = 9446;
  internalWebUIPort = 19446;

  # Helper script to handle connections
  vaultwardenConnectionHandler = pkgs.writeShellScript "vaultwarden-connection-handler" ''
    echo "Connection received at $(date)" >&2

    # Check if Vaultwarden container is running
    if ! ${pkgs.systemd}/bin/systemctl is-active --quiet docker-vaultwarden.service; then
      echo "Starting Vaultwarden..." >&2
      ${pkgs.systemd}/bin/systemctl start docker-vaultwarden.service

      # Wait for Vaultwarden to be ready
      echo "Waiting for Vaultwarden to start..." >&2
      for i in $(seq 1 30); do
        if ${pkgs.curl}/bin/curl -s -f --connect-timeout 2 http://127.0.0.1:${toString internalWebUIPort}/ >/dev/null 2>&1; then
          echo "Vaultwarden is ready!" >&2
          break
        fi
        if [ $i -eq 30 ]; then
          echo "Vaultwarden failed to start, sending error page" >&2
          cat << 'EOF'
HTTP/1.1 503 Service Unavailable
Content-Type: text/html
Connection: close

<!DOCTYPE html>
<html><head><title>Service Starting</title></head>
<body><h1>Vaultwarden is starting...</h1><p>Please wait a moment and refresh the page.</p></body></html>
EOF
          exit 1
        fi
        sleep 2
      done
    fi

    echo "Vaultwarden is ready, proxying connection..." >&2
    # Now proxy the connection to the running Vaultwarden
    exec ${pkgs.socat}/bin/socat - TCP:127.0.0.1:${toString internalWebUIPort}
  '';

in {
  sops.secrets."compose/vaultwarden.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "vaultwarden/server:latest";
    environmentFiles = [
      config.sops.secrets."compose/vaultwarden.env".path
    ];
    volumes = [
      "/media/HOMELAB_MEDIA/services/vaultwarden:/data:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:80/tcp"  # Internal port only
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=vaultwarden_default"
    ];
  };
  systemd.services."docker-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-vaultwarden_default.service"
    ];
    requires = [
      "docker-network-vaultwarden_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/vaultwarden"
    ];
    # Bind to root target
    partOf = [ "docker-compose-vaultwarden-root.target" ];
    wantedBy = [ "docker-compose-vaultwarden-root.target" ];
    # Start timer when service starts, stop when service stops
    postStart = ''
      ${pkgs.systemd}/bin/systemctl start vaultwarden-idle-stop.timer
    '';
    preStop = ''
      ${pkgs.systemd}/bin/systemctl stop vaultwarden-idle-stop.timer || true
    '';
  };

  # Networks
  systemd.services."docker-network-vaultwarden_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vaultwarden_default";
    };
    script = ''
      docker network inspect vaultwarden_default || docker network create vaultwarden_default
    '';
    partOf = [ "docker-compose-vaultwarden-root.target" ];
    wantedBy = [ "docker-compose-vaultwarden-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };

  # Port listener that starts Vaultwarden on any connection attempt
  systemd.services."vaultwarden-autostart" = {
    description = "Vaultwarden auto-start on connection";
    serviceConfig = {
      Restart = "always";
      RestartSec = "5s";
    };
    script = ''
      echo "Starting Vaultwarden auto-start proxy on port ${toString webUIPort}..."
      exec ${pkgs.socat}/bin/socat TCP4-LISTEN:${toString webUIPort},reuseaddr,fork EXEC:${vaultwardenConnectionHandler}
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/vaultwarden"
    ];
    # Bind to root target so it stops when target stops
    partOf = [ "docker-compose-vaultwarden-root.target" ];
    wantedBy = [ "docker-compose-vaultwarden-root.target" ];
    after = [ "docker.service" ];
  };

  # Timer-based service to stop when idle - started manually by docker-vaultwarden
  systemd.timers."vaultwarden-idle-stop" = {
    timerConfig = {
      OnCalendar = "*:0/5";  # Every 5 minutes, more explicit format
      Persistent = true;
      Unit = "vaultwarden-idle-stop.service";
    };
  };

  systemd.services."vaultwarden-idle-stop" = {
    serviceConfig = {
      Type = "oneshot";
    };
    script = ''
      # Check for active connections (both proxy port and internal port)
      proxy_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString webUIPort}" | grep ESTABLISHED | wc -l)
      internal_connections=$(${pkgs.unixtools.netstat}/bin/netstat -an | grep ":${toString internalWebUIPort}" | grep ESTABLISHED | wc -l)
      total_connections=$((proxy_connections + internal_connections))

      if [ "$total_connections" -eq 0 ]; then
        echo "$(date): No active connections for 5+ minutes, stopping Vaultwarden"
        ${pkgs.systemd}/bin/systemctl stop docker-vaultwarden.service
        # Timer will automatically stop due to partOf dependency
      else
        echo "$(date): $total_connections active connections, keeping Vaultwarden running"
      fi
    '';
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/vaultwarden"
    ];
    # Also bind to root target for additional safety
    partOf = [ "docker-compose-vaultwarden-root.target" ];
  };
}
