# Auto-generated using compose2nix v0.2.3.
{ pkgs, lib, config, ... }:

{
  sops.secrets."compose/vaultwarden.env" = {
    sopsFile = ./stack.env;
    format = "dotenv";
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."vaultwarden" = {
    image = "vaultwarden/server:latest";
    environmentFiles = [
      config.sops.secrets."compose/vaultwarden.env".path
    ];
    volumes = [
      "/media/HOMELAB_MEDIA/services/vaultwarden:/data:rw"
    ];
    ports = [
      "9446:80/tcp"
    ];
    user = "1000:1000";
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=vaultwarden"
      "--network=vaultwarden_default"
    ];
  };
  systemd.services."docker-vaultwarden" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-vaultwarden_default.service"
    ];
    requires = [
      "docker-network-vaultwarden_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "/media/HOMELAB_MEDIA/services/vaultwarden"
    ];
  };

  # Networks
  systemd.services."docker-network-vaultwarden_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f vaultwarden_default";
    };
    script = ''
      docker network inspect vaultwarden_default || docker network create vaultwarden_default
    '';
    partOf = [ "docker-compose-vaultwarden-root.target" ];
    wantedBy = [ "docker-compose-vaultwarden-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-vaultwarden-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
}
