# Auto-generated using compose2nix v0.3.2.
{ pkgs, lib, config, homelabMediaPath, ... }:

let
  webUIPort = 8083;
  internalWebUIPort = 18083;

  lazyLoadingLib = import ../lib/lazy-loading.nix { inherit pkgs lib; };

  lazyLoadingServices = lazyLoadingLib.mkLazyLoadingServices {
    serviceName = "Calibre Web Automated";
    dockerServiceName = "calibre-web-automated";
    webUIPort = webUIPort;
    internalPort = internalWebUIPort;
    requiredMounts = [
      "${homelabMediaPath}/services/calibre/config"
      "${homelabMediaPath}/services/calibre/ingest"
      "${homelabMediaPath}/services/calibre/library"
      "${homelabMediaPath}/services/calibre/plugins"
    ];
  };

in lib.mkMerge [
  lazyLoadingServices
  {
  sops.secrets = {
    "compose/calibre-web-automated.env" = {
      sopsFile = ./stack.env;
      format = "dotenv";
    };
  };

  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."calibre-web-automated" = {
    image = "crocodilestick/calibre-web-automated:latest";
    environment = {
      "CWA_PORT_OVERRIDE" = "8083";
      "NETWORK_SHARE_MODE" = "false";
      "PGID" = "1000";
      "PUID" = "1000";
      "TZ" = "Asia/Kolkata";
    };
    environmentFiles = [
      config.sops.secrets."compose/calibre-web-automated.env".path
    ];
    volumes = [
      "${homelabMediaPath}/services/calibre/config:/config:rw"
      "${homelabMediaPath}/services/calibre/ingest:/cwa-book-ingest:rw"
      "${homelabMediaPath}/services/calibre/library:/calibre-library:rw"
      "${homelabMediaPath}/services/calibre/plugins:/config/.config/calibre/plugins:rw"
    ];
    ports = [
      "127.0.0.1:${toString internalWebUIPort}:8083/tcp"
    ];
    log-driver = "journald";
    autoStart = false;
    extraOptions = [
      "--network-alias=calibre-web-automated"
      "--network=calibre-web-automated_default"
    ];
  };
  systemd.services."docker-calibre-web-automated" = {
    serviceConfig = {
      Restart = lib.mkOverride 500 "always";
      RestartMaxDelaySec = lib.mkOverride 500 "1m";
      RestartSec = lib.mkOverride 500 "100ms";
      RestartSteps = lib.mkOverride 500 9;
    };
    after = [
      "docker-network-calibre-web-automated_default.service"
    ];
    requires = [
      "docker-network-calibre-web-automated_default.service"
    ];
    unitConfig.RequiresMountsFor = [
      "${homelabMediaPath}/services/calibre/config"
      "${homelabMediaPath}/services/calibre/ingest"
      "${homelabMediaPath}/services/calibre/library"
      "${homelabMediaPath}/services/calibre/plugins"
    ];
    partOf = [ "docker-compose-calibre-web-automated-root.target" ];
    wantedBy = [ "docker-compose-calibre-web-automated-root.target" ];
  };

  # Networks
  systemd.services."docker-network-calibre-web-automated_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f calibre-web-automated_default";
    };
    script = ''
      docker network inspect calibre-web-automated_default || docker network create calibre-web-automated_default
    '';
    partOf = [ "docker-compose-calibre-web-automated-root.target" ];
    wantedBy = [ "docker-compose-calibre-web-automated-root.target" ];
  };

  # Root service
  systemd.targets."docker-compose-calibre-web-automated-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
  };
} ]
