name: generators
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: "Build: .#minimal-iso"
        run: |
          nix build .#minimal-iso
      # - name: Upload .#minimal-iso
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: minimal.iso
      #     path: ./result/iso/nixos.iso
      - name: "Build: .#minimal-install-iso"
        run: |
          nix build .#minimal-install-iso
      # - name: Upload .#minimal-install-iso
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: minimal-install.iso
      #     path: ./result/iso/nixos-*.iso

  mishy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          verbose: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
      # Derivations are built under /tmp
      - name: Bind mount /tmp
        run: |
          sudo mkdir /mnt/nix /nix
          sudo chmod 0755 /nix
          sudo mount --bind /mnt/nix /nix
      # - name: Set swap space
      #   uses: pierotofy/set-swap-space@master
      #   with:
      #     swap-size-gb: 10
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: "Build: .#mishi-raw-efi"
        run: |
          nix build .#mishy-raw-efi

  stashy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          verbose: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
      # Derivations are built under /tmp
      - name: Bind mount /tmp
        run: |
          sudo mkdir /mnt/nix /nix
          sudo chmod 0755 /nix
          sudo mount --bind /mnt/nix /nix
      # - name: Set swap space
      #   uses: pierotofy/set-swap-space@master
      #   with:
      #     swap-size-gb: 10
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: "extra-platforms = aarch64-linux"
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build: .#stashy-sd"
        run: |
          nix build .#stashy-sd

  nutcracker:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          verbose: 'true'
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-cached-tools: 'true'
          remove-swapfile: 'true'
      # Derivations are built under /tmp
      - name: Bind mount /tmp
        run: |
          sudo mkdir /mnt/nix /nix
          sudo chmod 0755 /nix
          sudo mount --bind /mnt/nix /nix
      # - name: Set swap space
      #   uses: pierotofy/set-swap-space@master
      #   with:
      #     swap-size-gb: 10
      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          extra_nix_config: "extra-platforms = aarch64-linux"
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: "Build: .#nutcracker-sd"
        run: |
          nix build .#nutcracker-sd
