name: generators
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  minimal-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v26
      #   with:
      #     nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4
      - name: minimal-iso
        run: |
          nix build .#minimal-iso

  minimal-install-iso:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      #   with:
      #     nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4
      - name: minimal-install-iso
        run: |
          nix build .#minimal-install-iso
