name: generators
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - name: Install Nix
        uses: cachix/install-nix-action@v27
      - name: Clone Repository
        uses: actions/checkout@v4
      - name: Build .#minimal-iso
        run: |
          nix build .#minimal-iso
      - name: Upload .#minimal-iso
        uses: actions/upload-artifact@v4
        with:
          name: minimal.iso
          path: ./result/iso/nixos.iso
      - name: Build .#minimal-install-iso
        run: |
          nix build .#minimal-install-iso
      - name: Upload .#minimal-install-iso
        uses: actions/upload-artifact@v4
        with:
          name: minimal-install.iso
          path: ./result/iso/nixos-*.iso
