name: Nix Setup

on:
  workflow_call: {}

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: AdityaGarg8/remove-unwanted-software@v4.1
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
      # - uses: pierotofy/set-swap-space@master
      #   with:
      #     swap-size-gb: 10
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        # with:
        #   nix_path: nixpkgs=channel:nixos-unstable
